# ==============================================================================
# Merged Lakeflow Source: hackathon_austin_texas
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from typing import Any, Iterator, Sequence
import json
import time

from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.streaming.datasource import ReadAllAvailable, SupportsTriggerAvailableNow
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
from requests.exceptions import RequestException
import base64
import requests


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Micro-batch sizing (by row count, time window, etc.) is entirely the
            connector's responsibility — use table_options (e.g. ``window_days``,
            ``max_records_per_batch``) to control it.  The framework always
            requests "all available" and does not pass an admission-control
            hint here.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current committed offset.  ``{}`` on the very
                    first call (from ``initialOffset``), then the last returned
                    end_offset on each subsequent call.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_namespaces.py
    ########################################################

    class SupportsNamespaces(ABC):
        """Mixin for connectors whose tables live under hierarchical namespaces.

        A namespace is a path of zero or more string segments (e.g. ``["org",
        "repo"]`` for GitHub, ``["tenant", "project"]`` for Azure DevOps).
        Connectors with a flat catalog do not need this mixin — the framework
        falls back to :meth:`LakeflowConnect.list_tables` and reports each table
        with an empty namespace.

        Output ordering on the ``_community_namespaces`` and ``_community_tables``
        Spark virtual tables is normalized by the framework via ``sorted(...)``,
        so connector implementations of :meth:`list_namespaces` and
        :meth:`list_tables_in_namespace` are free to return their results in
        any order (including from a :class:`set` or generator).

        Must be used together with :class:`LakeflowConnect`.

        Usage::

            class MyConnector(LakeflowConnect, SupportsNamespaces):
                ...
        """

        @abstractmethod
        def list_namespaces(
            self,
            prefix: list[str] | None = None,
        ) -> list[list[str]]:
            """Return the immediate child namespaces under ``prefix``.

            This method returns one level of *namespace* children only — it
            never returns tables. A namespace can hold tables and child
            namespaces independently; callers must always call
            :meth:`list_tables_in_namespace` for every namespace they care
            about, regardless of whether :meth:`list_namespaces` returned
            children for it. An empty return value just means there are no
            further child namespaces under ``prefix``.

            Walk the full tree by recursing on each returned child.

            Args:
                prefix: A namespace path under which to list children. ``None`` or
                    an empty list lists the root-level namespaces.
            Returns:
                A list of full namespace paths (each path includes the prefix).
            """

        @abstractmethod
        def list_tables_in_namespace(
            self,
            namespace: list[str],
        ) -> list[str]:
            """Return the table names that live directly under ``namespace``.

            Callers that want every table across the whole catalog walk the
            namespace tree via :meth:`list_namespaces` and call this method
            once per leaf — there is no "list everything" shortcut.

            Args:
                namespace: The namespace path. An empty list ``[]`` selects
                    root-level tables (those that live outside any namespace).
            Returns:
                A list of table names. The full ``(namespace, table_name)``
                row exposed on ``_community_tables`` is reconstructed by the
                framework from the namespace the caller already supplied, so
                the connector does not need to echo it back.
            """


    ########################################################
    # src/databricks\labs\community_connector\sources\hackathon_austin_texas\hackathon_austin_texas_schemas.py
    ########################################################

    DEFAULT_BASE_URL = "https://data.austintexas.gov"
    DEFAULT_TIMEOUT = 30  # seconds

    RETRIABLE_STATUS_CODES = {429, 500, 502, 503, 504}
    MAX_RETRIES = 5
    INITIAL_BACKOFF = 1.0  # seconds; doubled after each retry

    # Socrata caps a single page at 50,000 rows; 1,000 is a friendly default.
    DEFAULT_PAGE_SIZE = 1000
    MAX_PAGE_SIZE = 50000

    # Partitioning defaults.
    DEFAULT_WINDOW_DAYS = 1
    DEFAULT_LOOKBACK_MINUTES = 0

    # Sentinels for the incremental time cursor (``:updated_at``).
    EPOCH_ISO = "1970-01-01T00:00:00.000Z"
    # Any start cursor at or before this is treated as a first (full) run and
    # collapsed into a single open-ended partition instead of ~20k daily windows.
    FIRST_RUN_SENTINEL_THRESHOLD = "2000-01-01T00:00:00.000Z"

    # ---------------------------------------------------------------------------
    # Table -> Socrata dataset (4x4) mapping
    # ---------------------------------------------------------------------------

    DATASET_IDS: dict[str, str] = {
        "transportation_and_mobility": "28ys-ieqv",
        "green_building_ratings_aggregate": "dpvb-c5fy",
        "solar_program_current_incentive_levels_and_available_capacity": "vxq2-zjmn",
        "green_building_energy_code_compliance": "i7vh-fpaj",
        "green_building_developer_agreements": "63mb-dbmj",
        "coa_energy_codes_timeline": "xn7p-rafv",
        "discount_monthly_new_enrollment_by_zip": "guem-bnpv",
    }

    TABLES: list[str] = list(DATASET_IDS.keys())

    # Renamed Socrata system field names, shared by every table.
    SYSTEM_ID = "system_id"
    SYSTEM_CREATED_AT = "system_created_at"
    SYSTEM_UPDATED_AT = "system_updated_at"
    CURSOR_FIELD = SYSTEM_UPDATED_AT

    # Wire -> Spark name mapping for the three Socrata system fields.
    SYSTEM_FIELD_RENAMES = {
        ":id": SYSTEM_ID,
        ":created_at": SYSTEM_CREATED_AT,
        ":updated_at": SYSTEM_UPDATED_AT,
    }

    # URL fields that arrive as a ``{"url": "..."}`` struct, per table.
    URL_STRUCT_FIELDS: dict[str, list[str]] = {
        "transportation_and_mobility": ["dataset_url"],
        "green_building_developer_agreements": ["ordinance_"],
    }


    def _url_struct() -> StructType:
        return StructType([StructField("url", StringType(), True)])


    def _system_fields() -> list[StructField]:
        """The three Socrata system columns prepended to every table schema."""
        return [
            StructField(SYSTEM_ID, StringType(), True),
            StructField(SYSTEM_CREATED_AT, TimestampType(), True),
            StructField(SYSTEM_UPDATED_AT, TimestampType(), True),
        ]


    # ---------------------------------------------------------------------------
    # Per-table schemas
    # ---------------------------------------------------------------------------

    _TRANSPORTATION_AND_MOBILITY = StructType(
        _system_fields()
        + [
            StructField("id", StringType(), True),
            StructField("name", StringType(), True),
            StructField("description", StringType(), True),
            StructField("dataset_url", _url_struct(), True),
            StructField("attribution", StringType(), True),
            StructField("type", StringType(), True),
            StructField("update_frequency", StringType(), True),
            StructField("department_name", StringType(), True),
            StructField("program_name", StringType(), True),
            StructField("spatial_information", StringType(), True),
            StructField("strategic_area", StringType(), True),
            StructField("updatedat", TimestampType(), True),
            StructField("createdat", TimestampType(), True),
            StructField("metadata_updated_at", TimestampType(), True),
            StructField("data_updated_at", TimestampType(), True),
            StructField("publication_date", TimestampType(), True),
            StructField("download_count", LongType(), True),
            StructField("page_views_last_week", LongType(), True),
            StructField("page_views_last_month", LongType(), True),
            StructField("page_views_total", LongType(), True),
            StructField("row_count", LongType(), True),
            StructField("cover_image_url", StringType(), True),
            StructField("automation_method", StringType(), True),
            StructField("automation_method_other", StringType(), True),
            StructField("owner_display_name", StringType(), True),
            StructField("tags", StringType(), True),
            StructField("is_public", BooleanType(), True),
        ]
    )

    _GREEN_BUILDING_RATINGS_AGGREGATE = StructType(
        _system_fields()
        + [
            StructField("class", StringType(), True),
            StructField("fiscal_year", StringType(), True),
            StructField("number_of_projects_aegb_rated", LongType(), True),
            StructField("number_of_projects_leed_reported", LongType(), True),
            StructField("total_square_footage_aegb_rated_projects", DoubleType(), True),
            StructField("number_of_residential_units_aegb_rated", LongType(), True),
            StructField("number_of_smart_housing_units_aegb_rated", LongType(), True),
            StructField("estimated_energy_savings_mbtu", DoubleType(), True),
            StructField("estimated_demand_savings_kw", DoubleType(), True),
            StructField("estimated_electric_energy_savings_kwh", DoubleType(), True),
            # Typed as text in the source despite looking numeric — kept as string.
            StructField("pv_generation_mwh_", StringType(), True),
            StructField("gas_savings_ccf", DoubleType(), True),
            StructField("indoor_potable_water_reduction_gallons", DoubleType(), True),
            StructField(
                "irrigation_potable_water_reduction_gallons_month_of_july",
                DoubleType(),
                True,
            ),
            StructField("process_portable_water_reduction_1000_gallons_", DoubleType(), True),
            StructField(
                "construction_waste_diverted_from_landfill_tons", DoubleType(), True
            ),
            StructField(
                "number_of_aegb_rated_residential_units_outside_ae_service",
                LongType(),
                True,
            ),
            StructField(
                "number_of_aegb_rated_units_in_s_m_a_r_t_developments_outside_ae_service",
                LongType(),
                True,
            ),
            StructField("projects_sq_ft_outside_ae_service", DoubleType(), True),
            StructField("_of_rated_projects_outside_of_ae_service_area", LongType(), True),
            StructField("start_date", TimestampType(), True),
            StructField("end_date", TimestampType(), True),
        ]
    )

    _SOLAR_PROGRAM = StructType(
        _system_fields()
        + [
            StructField("program", StringType(), True),
            StructField("capacity_requested_kw_ac", DoubleType(), True),
            StructField("capacity_reserved_kw_ac", DoubleType(), True),
            StructField("capacity_available_kw_ac", DoubleType(), True),
            StructField("date_last_updated", TimestampType(), True),
        ]
    )

    _GREEN_BUILDING_ENERGY_CODE_COMPLIANCE = StructType(
        _system_fields()
        + [
            StructField("fiscal_year", StringType(), True),
            StructField("number_of_residential_building_permits", LongType(), True),
            StructField("residential_energy_code_savings_kw", DoubleType(), True),
            StructField("residential_energy_code_savings_mwh", DoubleType(), True),
            StructField("number_of_multifamily_unit_permits", LongType(), True),
            StructField("multifamily_energy_code_savings_kw", DoubleType(), True),
            StructField("multifamily_energy_code_savings_mwh", DoubleType(), True),
            StructField("square_footage_of_commercial_building_permits", DoubleType(), True),
            StructField("commercial_energy_code_savings_kw", DoubleType(), True),
            StructField("commercial_energy_code_savings_mwh", DoubleType(), True),
            StructField("start_date", TimestampType(), True),
            StructField("end_date", TimestampType(), True),
            StructField("total_energy_code_saving", DoubleType(), True),
            StructField("total_energy_code_savings_mwh_", DoubleType(), True),
        ]
    )

    _GREEN_BUILDING_DEVELOPER_AGREEMENTS = StructType(
        _system_fields()
        + [
            # GeoJSON MultiPolygon kept as a JSON string for schema stability.
            StructField("the_geom_json", StringType(), True),
            StructField("gis_id", LongType(), True),
            StructField("name", StringType(), True),
            StructField("ordinance_", _url_struct(), True),
            StructField("created_da", TimestampType(), True),
            StructField("shape_area", DoubleType(), True),
            StructField("shape_len", DoubleType(), True),
        ]
    )

    _COA_ENERGY_CODES_TIMELINE = StructType(
        _system_fields()
        + [
            StructField("effective_date", TimestampType(), True),
            StructField("city_of_austin_energy_code", LongType(), True),
            StructField("residential_energy_code", StringType(), True),
            StructField("commercial_energy_code", StringType(), True),
            StructField("residential_ordinance", StringType(), True),
            StructField("commercial_ordinance", StringType(), True),
            StructField("energy_code_name", StringType(), True),
            StructField("line", LongType(), True),
        ]
    )

    _DISCOUNT_MONTHLY_NEW_ENROLLMENT_BY_ZIP = StructType(
        _system_fields()
        + [
            StructField("zip_code", StringType(), True),
            StructField("oct_23", LongType(), True),
            StructField("nov_23", LongType(), True),
            StructField("dec_23", LongType(), True),
            StructField("jan_24", LongType(), True),
            StructField("feb_24", LongType(), True),
            StructField("mar_24", LongType(), True),
            StructField("apr_24", LongType(), True),
            StructField("may_24", LongType(), True),
            StructField("jun_24", LongType(), True),
            StructField("jul_24", LongType(), True),
            StructField("aug_24", LongType(), True),
            StructField("sep_24", LongType(), True),
        ]
    )


    TABLE_SCHEMAS: dict[str, StructType] = {
        "transportation_and_mobility": _TRANSPORTATION_AND_MOBILITY,
        "green_building_ratings_aggregate": _GREEN_BUILDING_RATINGS_AGGREGATE,
        "solar_program_current_incentive_levels_and_available_capacity": _SOLAR_PROGRAM,
        "green_building_energy_code_compliance": _GREEN_BUILDING_ENERGY_CODE_COMPLIANCE,
        "green_building_developer_agreements": _GREEN_BUILDING_DEVELOPER_AGREEMENTS,
        "coa_energy_codes_timeline": _COA_ENERGY_CODES_TIMELINE,
        "discount_monthly_new_enrollment_by_zip": _DISCOUNT_MONTHLY_NEW_ENROLLMENT_BY_ZIP,
    }


    # ---------------------------------------------------------------------------
    # Per-table metadata
    # ---------------------------------------------------------------------------
    #
    # All tables are ``cdc`` keyed on the Socrata ``:updated_at`` system field
    # (renamed ``system_updated_at``).  Socrata exposes no delete feed, so
    # ``cdc_with_deletes`` is not used (hard-delete detection would require a
    # periodic full-snapshot reconciliation, out of scope here).  Primary keys use
    # the documented natural key where one exists, falling back to ``system_id``.
    TABLE_METADATA: dict[str, dict] = {
        "transportation_and_mobility": {
            "primary_keys": ["id"],
            "cursor_field": CURSOR_FIELD,
            "ingestion_type": "cdc",
        },
        "green_building_ratings_aggregate": {
            # Natural key is composite (class, fiscal_year); use the stable
            # Socrata surrogate ``system_id`` as a single-column PK.
            "primary_keys": [SYSTEM_ID],
            "cursor_field": CURSOR_FIELD,
            "ingestion_type": "cdc",
        },
        "solar_program_current_incentive_levels_and_available_capacity": {
            "primary_keys": ["program"],
            "cursor_field": CURSOR_FIELD,
            "ingestion_type": "cdc",
        },
        "green_building_energy_code_compliance": {
            "primary_keys": ["fiscal_year"],
            "cursor_field": CURSOR_FIELD,
            "ingestion_type": "cdc",
        },
        "green_building_developer_agreements": {
            "primary_keys": ["gis_id"],
            "cursor_field": CURSOR_FIELD,
            "ingestion_type": "cdc",
        },
        "coa_energy_codes_timeline": {
            # No confirmed unique natural key; use the Socrata surrogate.
            "primary_keys": [SYSTEM_ID],
            "cursor_field": CURSOR_FIELD,
            "ingestion_type": "cdc",
        },
        "discount_monthly_new_enrollment_by_zip": {
            "primary_keys": ["zip_code"],
            "cursor_field": CURSOR_FIELD,
            "ingestion_type": "cdc",
        },
    }


    # ---------------------------------------------------------------------------
    # Numeric coercion maps (Socrata returns numbers as JSON strings)
    # ---------------------------------------------------------------------------


    def _build_coercion_map() -> dict[str, dict[str, str]]:
        """Map each table's LongType/DoubleType leaf columns to a coercion kind."""
        out: dict[str, dict[str, str]] = {}
        for table, schema in TABLE_SCHEMAS.items():
            kinds: dict[str, str] = {}
            for f in schema.fields:
                if isinstance(f.dataType, LongType):
                    kinds[f.name] = "long"
                elif isinstance(f.dataType, DoubleType):
                    kinds[f.name] = "double"
            out[table] = kinds
        return out


    COERCION_MAP: dict[str, dict[str, str]] = _build_coercion_map()


    ########################################################
    # src/databricks/labs/community_connector/sources/hackathon_austin_texas/hackathon_austin_texas.py
    ########################################################

    _ERROR_BODY_LIMIT = 500


    class HackathonAustinTexasLakeflowConnect(LakeflowConnect, SupportsPartitionedStream):
        """LakeflowConnect + SupportsPartitionedStream for data.austintexas.gov (Socrata)."""

        def __init__(self, options: dict[str, str]) -> None:
            super().__init__(options)

            self._base_url = (options.get("base_url") or DEFAULT_BASE_URL).rstrip("/")
            # App token is optional: public datasets read without one, but a token
            # lifts the connector out of the shared per-IP throttle.
            self._app_token = options.get("app_token") or options.get("X-App-Token")

            try:
                self._page_size = max(
                    1,
                    min(MAX_PAGE_SIZE, int(options.get("page_size") or DEFAULT_PAGE_SIZE)),
                )
            except (TypeError, ValueError):
                self._page_size = DEFAULT_PAGE_SIZE

            # Freeze the high-water mark at init time so incremental reads return a
            # stable cursor across microbatches within one Trigger.AvailableNow
            # run — this is what guarantees termination.  A later trigger builds a
            # fresh instance with a newer cap and picks up anything that arrived.
            self._init_time = self._format_iso(datetime.now(timezone.utc))

        # ------------------------------------------------------------------
        # LakeflowConnect — schema / metadata
        # ------------------------------------------------------------------

        def list_tables(self) -> list[str]:
            """Static object list — a curated set of seven City of Austin datasets."""
            return list(TABLES)

        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            self._validate_table(table_name)
            return TABLE_SCHEMAS[table_name]

        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            self._validate_table(table_name)
            return dict(TABLE_METADATA[table_name])

        # ------------------------------------------------------------------
        # SupportsPartitionedStream
        # ------------------------------------------------------------------

        def is_partitioned(self, table_name: str) -> bool:
            return table_name in TABLES

        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the high-water mark, capped at the init-time snapshot.

            Kept metadata-cheap: it returns the frozen ``_init_time`` rather than
            querying the source.  Once a stream catches up to this value,
            successive calls return it unchanged and Trigger.AvailableNow
            terminates.
            """
            self._validate_table(table_name)
            return {"cursor": self._init_time}

        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Split the ``(start, end]`` ``:updated_at`` range into time windows."""
            self._validate_table(table_name)

            window_days = self._parse_int(
                table_options.get("window_days"), DEFAULT_WINDOW_DAYS, minimum=1
            )
            lookback_minutes = self._parse_int(
                table_options.get("lookback_minutes"),
                DEFAULT_LOOKBACK_MINUTES,
                minimum=0,
            )

            if start_offset is None and end_offset is None:
                # Batch read — cover the whole table.
                start_iso = EPOCH_ISO
                end_iso = self._init_time
            else:
                start_iso = (start_offset or {}).get("cursor") or EPOCH_ISO
                end_iso = (end_offset or {}).get("cursor") or self._init_time

            start_dt = self._parse_iso(start_iso)
            end_dt = self._parse_iso(end_iso)
            if start_dt >= end_dt:
                return []

            # First-run optimisation: a single open-ended partition for the
            # backfill instead of one window per day back to the epoch.
            if start_dt <= self._parse_iso(FIRST_RUN_SENTINEL_THRESHOLD):
                return [{"since": EPOCH_ISO, "until": end_iso}]

            if lookback_minutes > 0:
                start_iso = self._format_iso(
                    start_dt - timedelta(minutes=lookback_minutes)
                )
                start_dt = self._parse_iso(start_iso)
                if start_dt >= end_dt:
                    return []

            partitions: list[dict] = []
            cursor_iso = start_iso
            cursor_dt = start_dt
            while cursor_dt < end_dt:
                next_dt = cursor_dt + timedelta(days=window_days)
                if next_dt > end_dt:
                    next_dt = end_dt
                    next_iso = end_iso
                else:
                    next_iso = self._format_iso(next_dt)
                partitions.append({"since": cursor_iso, "until": next_iso})
                cursor_iso = next_iso
                cursor_dt = next_dt

            return partitions

        def read_partition(
            self,
            table_name: str,
            partition: dict,
            table_options: dict[str, str],
        ) -> Iterator[dict]:
            """Read one ``(since, until]`` window on an executor."""
            self._validate_table(table_name)
            since = partition.get("since", EPOCH_ISO)
            until = partition.get("until", self._init_time)
            yield from self._fetch_window(table_name, since, until)

        # ------------------------------------------------------------------
        # LakeflowConnect.read_table — single-driver fallback
        # ------------------------------------------------------------------

        def read_table(
            self,
            table_name: str,
            start_offset: dict,
            table_options: dict[str, str],
        ) -> tuple[Iterator[dict], dict]:
            """Single-driver incremental read (used when partitioning is off).

            Reads everything in ``(start_cursor, init_time]`` in one batch and
            advances the offset to ``init_time`` — the next call then returns an
            empty batch with the same offset, terminating the trigger.
            """
            self._validate_table(table_name)

            since = (start_offset or {}).get("cursor") or EPOCH_ISO
            if self._parse_iso(since) >= self._parse_iso(self._init_time):
                return iter([]), start_offset or {"cursor": self._init_time}

            records = list(self._fetch_window(table_name, since, self._init_time))
            return iter(records), {"cursor": self._init_time}

        # ------------------------------------------------------------------
        # HTTP + record shaping
        # ------------------------------------------------------------------

        def _fetch_window(
            self, table_name: str, since: str, until: str
        ) -> Iterator[dict]:
            """Yield transformed records for a single ``:updated_at`` window.

            Paginates the Socrata resource with ``$offset`` / ``$limit`` until a
            short page signals the end of the window.
            """
            dataset_id = DATASET_IDS[table_name]
            where = self._build_where(since, until)

            offset = 0
            while True:
                params = {
                    # ``:*,*`` selects the Socrata system fields alongside the
                    # published columns so ``:updated_at`` is available as a cursor.
                    "$select": ":*,*",
                    "$where": where,
                    "$order": ":updated_at",
                    "$limit": str(self._page_size),
                    "$offset": str(offset),
                }
                resp = self._request(dataset_id, params)
                if resp.status_code != 200:
                    raise RuntimeError(
                        f"Socrata request for {table_name!r} ({dataset_id}) failed: "
                        f"{resp.status_code} {self._redact(resp.text)}"
                    )

                batch = resp.json()
                if not isinstance(batch, list):
                    raise RuntimeError(
                        f"Unexpected Socrata response shape for {table_name!r}: "
                        f"expected a JSON array, got {type(batch).__name__}"
                    )
                if not batch:
                    return

                for raw in batch:
                    yield self._transform_record(table_name, raw)

                if len(batch) < self._page_size:
                    return
                offset += self._page_size

        def _request(self, dataset_id: str, params: dict[str, str]) -> requests.Response:
            """GET ``/resource/{4x4}.json`` with retry on transient failures.

            A fresh ``requests.get`` per call keeps the connector free of
            non-picklable state so it ships cleanly to Spark executors.
            """
            url = f"{self._base_url}/resource/{dataset_id}.json"
            headers = {"Accept": "application/json"}
            if self._app_token:
                headers["X-App-Token"] = self._app_token

            backoff = INITIAL_BACKOFF
            resp: requests.Response | None = None
            last_exc: RequestException | None = None
            for attempt in range(MAX_RETRIES):
                try:
                    resp = requests.get(
                        url, params=params, headers=headers, timeout=DEFAULT_TIMEOUT
                    )
                except RequestException as exc:
                    last_exc = exc
                else:
                    if resp.status_code not in RETRIABLE_STATUS_CODES:
                        return resp
                if attempt < MAX_RETRIES - 1:
                    sleep_for = backoff
                    if resp is not None:
                        retry_after = resp.headers.get("Retry-After", "").strip()
                        if retry_after:
                            try:
                                sleep_for = max(sleep_for, float(retry_after))
                            except ValueError:
                                pass
                    time.sleep(sleep_for)
                    backoff *= 2

            if resp is None and last_exc is not None:
                raise RuntimeError(
                    f"Socrata request failed after {MAX_RETRIES} attempts "
                    f"for {dataset_id}: {last_exc}"
                ) from last_exc
            return resp

        def _transform_record(self, table_name: str, raw: Any) -> dict:
            """Normalise a raw Socrata row into the shape declared by the schema.

            * Rename the three system fields (``:id`` etc.) to their colon-free
              Spark column names (tolerant of an already-renamed simulator row).
            * Serialise ``the_geom`` (GeoJSON) to ``the_geom_json``.
            * Normalise URL fields to a ``{"url": ...}`` struct.
            * Coerce Socrata's string-encoded numbers to their declared type.
            """
            if not isinstance(raw, dict):
                return {}
            record = dict(raw)

            for wire_name, spark_name in SYSTEM_FIELD_RENAMES.items():
                if wire_name in record:
                    record[spark_name] = record.pop(wire_name)

            if "the_geom" in record:
                geom = record.pop("the_geom")
                record["the_geom_json"] = (
                    geom if isinstance(geom, str) else self._json_or_none(geom)
                )

            for url_field in URL_STRUCT_FIELDS.get(table_name, []):
                value = record.get(url_field)
                if isinstance(value, str):
                    record[url_field] = {"url": value}

            for field_name, kind in COERCION_MAP.get(table_name, {}).items():
                if field_name in record:
                    if kind == "long":
                        record[field_name] = self._coerce_long(record[field_name])
                    else:
                        record[field_name] = self._coerce_double(record[field_name])

            return record

        # ------------------------------------------------------------------
        # Helpers
        # ------------------------------------------------------------------

        def _validate_table(self, table_name: str) -> None:
            if table_name not in TABLES:
                raise ValueError(
                    f"Table '{table_name}' is not supported. Supported tables: {TABLES}"
                )

        def _build_where(self, since: str, until: str) -> str:
            """Build the SoQL ``$where`` clause over ``:updated_at``.

            The first run (``since`` at/before the epoch) has no lower bound so it
            catches every historical row.  Non-first windows use an exclusive lower
            bound so back-to-back windows are disjoint — a boundary row belongs to
            exactly one window.
            """
            until_lit = self._soql_literal(until)
            if self._parse_iso(since) <= self._parse_iso(EPOCH_ISO):
                return f":updated_at <= '{until_lit}'"
            since_lit = self._soql_literal(since)
            return f":updated_at > '{since_lit}' AND :updated_at <= '{until_lit}'"

        @staticmethod
        def _soql_literal(iso_ts: str) -> str:
            """Render an ISO timestamp as a Socrata floating-timestamp literal."""
            dt = HackathonAustinTexasLakeflowConnect._parse_iso(iso_ts)
            return dt.strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3]

        @staticmethod
        def _parse_int(value: Any, default: int, *, minimum: int = 0) -> int:
            try:
                parsed = int(value)
            except (TypeError, ValueError):
                return default
            return parsed if parsed >= minimum else default

        @staticmethod
        def _parse_iso(iso_ts: str) -> datetime:
            """Parse an ISO timestamp, tolerating a trailing ``Z`` and naive values."""
            text = (iso_ts or EPOCH_ISO).strip()
            if text.endswith("Z"):
                text = text[:-1] + "+00:00"
            try:
                dt = datetime.fromisoformat(text)
            except ValueError as exc:
                raise ValueError(f"Invalid ISO timestamp {iso_ts!r}") from exc
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=timezone.utc)
            return dt.astimezone(timezone.utc)

        @staticmethod
        def _format_iso(dt: datetime) -> str:
            """Format a datetime as ``YYYY-MM-DDTHH:MM:SS.mmmZ`` (UTC)."""
            dt = dt.astimezone(timezone.utc)
            return dt.strftime("%Y-%m-%dT%H:%M:%S.") + f"{dt.microsecond // 1000:03d}Z"

        @staticmethod
        def _redact(text: str) -> str:
            if not text:
                return ""
            flat = text.replace("\r", " ").replace("\n", " ")
            if len(flat) <= _ERROR_BODY_LIMIT:
                return flat
            return flat[:_ERROR_BODY_LIMIT] + "...[truncated]"

        @staticmethod
        def _json_or_none(value: Any) -> str | None:
            if value is None:
                return None
            try:
                return json.dumps(value, ensure_ascii=False)
            except (TypeError, ValueError):
                return None

        @staticmethod
        def _coerce_long(value: Any) -> int | None:
            if value is None or value == "":
                return None
            if isinstance(value, bool):
                return int(value)
            if isinstance(value, int):
                return value
            try:
                return int(float(value))
            except (TypeError, ValueError):
                return None

        @staticmethod
        def _coerce_double(value: Any) -> float | None:
            if value is None or value == "":
                return None
            if isinstance(value, bool):
                return float(value)
            if isinstance(value, (int, float)):
                return float(value)
            try:
                return float(value)
            except (TypeError, ValueError):
                return None


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = HackathonAustinTexasLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_community_table_metadata"
    NAMESPACES_TABLE = "_community_namespaces"
    TABLES_TABLE = "_community_tables"
    VIRTUAL_TABLES = (METADATA_TABLE, NAMESPACES_TABLE, TABLES_TABLE)
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"
    NAMESPACE_PREFIX = "namespacePrefix"
    NAMESPACE = "namespace"


    def _decode_list_of_str_option(option_name: str, value: str | None) -> list[str] | None:
        """Decode and validate a JSON-encoded ``list[str]`` Spark option.

        Returns ``None`` if the option is absent; otherwise the parsed list.
        Raises ``ValueError`` with the offending value if the JSON is malformed
        or the decoded value is not a list of strings.
        """
        if value is None:
            return None
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, list) or not all(isinstance(s, str) for s in decoded):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got: {decoded!r}"
            )
        return decoded


    def _decode_dict_option(option_name: str, value: str | None) -> dict:
        """Decode and validate a JSON-encoded ``dict`` Spark option."""
        if value is None:
            return {}
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, dict):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; got: {decoded!r}"
            )
        return decoded


    # PySpark's DataSource API requires camelCase method names and inherits
    # semantics from the parent class, so per-method docstrings are redundant.
    # pylint: disable=invalid-name,missing-function-docstring
    class LakeflowStreamReader(SimpleDataSourceStreamReader, SupportsTriggerAvailableNow):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowPartitionedStreamReader(DataSourceStreamReader, SupportsTriggerAvailableNow):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def getDefaultReadLimit(self):
            # Admission control is the connector's responsibility (e.g. via
            # window_days, max_records_per_batch), not the engine's.  Always
            # ask the engine for ReadAllAvailable.
            return ReadAllAvailable()

        def latestOffset(self, start: dict, limit) -> dict:
            # We declared ReadAllAvailable via getDefaultReadLimit; the engine
            # must respect it.  Anything else means admission-control expectations
            # we do not support — fail loudly rather than silently ignore.
            if not isinstance(limit, ReadAllAvailable):
                raise ValueError(
                    f"LakeflowPartitionedStreamReader only supports ReadAllAvailable; "
                    f"got {type(limit).__name__}. Micro-batch sizing must be controlled "
                    f"by the connector implementation (table_options), not the engine."
                )
            return self.lakeflow_connect.latest_offset(
                self.table_name, self.table_options, start
            )

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name not in VIRTUAL_TABLES:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self.table_name == NAMESPACES_TABLE:
                records = self._read_namespaces()
            elif self.table_name == TABLES_TABLE:
                records = self._read_tables()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_names = _decode_list_of_str_option(
                TABLE_NAME_LIST, self.options.get(TABLE_NAME_LIST)
            ) or []
            table_configs = _decode_dict_option(
                TABLE_CONFIGS, self.options.get(TABLE_CONFIGS)
            )
            all_records = []
            # Preserve caller-supplied table order — caller controls it.
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records

        def _read_namespaces(self):
            # Connectors without SupportsNamespaces are flat — no rows.
            if not isinstance(self.lakeflow_connect, SupportsNamespaces):
                return []
            prefix = _decode_list_of_str_option(
                NAMESPACE_PREFIX, self.options.get(NAMESPACE_PREFIX)
            )
            namespaces = self.lakeflow_connect.list_namespaces(prefix)
            # Sort framework-side for deterministic output regardless of
            # connector iteration order.
            return [{"namespace": ns} for ns in sorted(namespaces)]

        def _read_tables(self):
            namespace_supplied = NAMESPACE in self.options
            if isinstance(self.lakeflow_connect, SupportsNamespaces):
                if not namespace_supplied:
                    raise ValueError(
                        f"option '{NAMESPACE}' is required when reading "
                        f"'{TABLES_TABLE}' against a connector that implements "
                        f"SupportsNamespaces. Pass a JSON-encoded list[str] "
                        f"(use '[]' for root-level tables; walk the tree via "
                        f"'{NAMESPACES_TABLE}' to enumerate every namespace)."
                    )
                namespace = _decode_list_of_str_option(
                    NAMESPACE, self.options[NAMESPACE]
                )
                tables = self.lakeflow_connect.list_tables_in_namespace(namespace)
                return [
                    {"namespace": namespace, TABLE_NAME: tn}
                    for tn in sorted(tables)
                ]
            # Flat connector path. Reject a stray `namespace` option — the
            # caller probably mistook this connector for namespace-aware and
            # silently ignoring the option would mask the bug.
            if namespace_supplied:
                raise ValueError(
                    f"option '{NAMESPACE}' was supplied but the connector does "
                    f"not implement SupportsNamespaces. Either omit the option "
                    f"or use a namespace-aware connector."
                )
            return [
                {"namespace": [], TABLE_NAME: tn}
                for tn in sorted(self.lakeflow_connect.list_tables())
            ]


    class LakeflowSource(DataSource):
        """
        PySpark DataSource base for Lakeflow Connect.

        Two ways the connector implementation is bound:

        - Per-source subclass (wheel / multi-file deployment): subclass and set
          ``_lakeflow_connect_cls``::

              class GmailDataSource(LakeflowSource):
                  _lakeflow_connect_cls = GmailLakeflowConnect

              spark.dataSource.register(GmailDataSource)

        - Merged single-file deployment (SDP): ``_lakeflow_connect_cls`` is left
          ``None`` and the connector is taken from the module-level
          ``LakeflowConnectImpl`` placeholder, which the merge script substitutes
          with the actual implementation class.
        """

        # Per-source subclasses set this. Left ``None`` on the base so the merged
        # single-file path falls back to the ``LakeflowConnectImpl`` placeholder.
        _lakeflow_connect_cls = None

        # Spark format name. Defaults to "lakeflow_connect" because Unity Catalog
        # connection-option injection looks for that exact string. A per-source
        # subclass may override this with its source name once it no longer relies
        # on UC injection (see the commented override in each source's __init__.py).
        _format_name = "lakeflow_connect"

        def __init__(self, options):
            self.options = options
            table = options.get(TABLE_NAME)
            # Catch typos against the framework's reserved virtual-table namespace
            # early — falling through to the connector with an unknown
            # `_community_*` name yields a confusing per-connector error.
            if table and table.startswith("_community_") and table not in VIRTUAL_TABLES:
                raise ValueError(
                    f"unknown framework virtual table '{table}'. Valid framework "
                    f"virtual tables are: {', '.join(VIRTUAL_TABLES)}. "
                    f"For a regular source table, use a name that does not start "
                    f"with '_community_'."
                )
            # Per-source subclasses bind the implementation via _lakeflow_connect_cls.
            # The merged single-file path leaves it None and relies on the
            # LakeflowConnectImpl placeholder (substituted by the merge script).
            connect_cls = type(self)._lakeflow_connect_cls or LakeflowConnectImpl
            self.lakeflow_connect = connect_cls(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return cls._format_name

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            if table == NAMESPACES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                    ]
                )
            if table == TABLES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                        StructField(TABLE_NAME, StringType(), False),
                    ]
                )
            return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
