# ==============================================================================
# Merged Lakeflow Source: google_maps_solar
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from datetime import datetime, timezone
from decimal import Decimal
from typing import Any, Iterator, Sequence
import json
import time

from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.streaming.datasource import ReadAllAvailable, SupportsTriggerAvailableNow
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
from requests.exceptions import RequestException
from urllib.parse import parse_qs, quote, urlsplit
import base64
import requests


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Micro-batch sizing (by row count, time window, etc.) is entirely the
            connector's responsibility — use table_options (e.g. ``window_days``,
            ``max_records_per_batch``) to control it.  The framework always
            requests "all available" and does not pass an admission-control
            hint here.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current committed offset.  ``{}`` on the very
                    first call (from ``initialOffset``), then the last returned
                    end_offset on each subsequent call.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_namespaces.py
    ########################################################

    class SupportsNamespaces(ABC):
        """Mixin for connectors whose tables live under hierarchical namespaces.

        A namespace is a path of zero or more string segments (e.g. ``["org",
        "repo"]`` for GitHub, ``["tenant", "project"]`` for Azure DevOps).
        Connectors with a flat catalog do not need this mixin — the framework
        falls back to :meth:`LakeflowConnect.list_tables` and reports each table
        with an empty namespace.

        Output ordering on the ``_community_namespaces`` and ``_community_tables``
        Spark virtual tables is normalized by the framework via ``sorted(...)``,
        so connector implementations of :meth:`list_namespaces` and
        :meth:`list_tables_in_namespace` are free to return their results in
        any order (including from a :class:`set` or generator).

        Must be used together with :class:`LakeflowConnect`.

        Usage::

            class MyConnector(LakeflowConnect, SupportsNamespaces):
                ...
        """

        @abstractmethod
        def list_namespaces(
            self,
            prefix: list[str] | None = None,
        ) -> list[list[str]]:
            """Return the immediate child namespaces under ``prefix``.

            This method returns one level of *namespace* children only — it
            never returns tables. A namespace can hold tables and child
            namespaces independently; callers must always call
            :meth:`list_tables_in_namespace` for every namespace they care
            about, regardless of whether :meth:`list_namespaces` returned
            children for it. An empty return value just means there are no
            further child namespaces under ``prefix``.

            Walk the full tree by recursing on each returned child.

            Args:
                prefix: A namespace path under which to list children. ``None`` or
                    an empty list lists the root-level namespaces.
            Returns:
                A list of full namespace paths (each path includes the prefix).
            """

        @abstractmethod
        def list_tables_in_namespace(
            self,
            namespace: list[str],
        ) -> list[str]:
            """Return the table names that live directly under ``namespace``.

            Callers that want every table across the whole catalog walk the
            namespace tree via :meth:`list_namespaces` and call this method
            once per leaf — there is no "list everything" shortcut.

            Args:
                namespace: The namespace path. An empty list ``[]`` selects
                    root-level tables (those that live outside any namespace).
            Returns:
                A list of table names. The full ``(namespace, table_name)``
                row exposed on ``_community_tables`` is reconstructed by the
                framework from the namespace the caller already supplied, so
                the connector does not need to echo it back.
            """


    ########################################################
    # src/databricks\labs\community_connector\sources\google_maps_solar\google_maps_solar_schemas.py
    ########################################################

    DEFAULT_BASE_URL = "https://solar.googleapis.com"
    API_VERSION = "v1"

    #: Timeout for the two JSON lookup endpoints.
    DEFAULT_TIMEOUT = 30
    #: GeoTIFF payloads can be a few MB, so they get a longer budget.
    GEO_TIFF_TIMEOUT = 120

    MAX_RETRIES = 4
    INITIAL_BACKOFF = 1.0
    #: 429 is the documented response when the shared 600 QPM quota is exceeded.
    RETRIABLE_STATUS_CODES = {429, 500, 502, 503, 504}

    # ----- table names --------------------------------------------------------

    TABLE_BUILDING_INSIGHTS = "building_insights"
    TABLE_DATA_LAYERS = "data_layers"
    TABLE_GEO_TIFF = "geo_tiff"

    TABLES = [TABLE_BUILDING_INSIGHTS, TABLE_DATA_LAYERS, TABLE_GEO_TIFF]

    # ----- endpoint paths -----------------------------------------------------

    PATH_BUILDING_INSIGHTS = f"/{API_VERSION}/buildingInsights:findClosest"
    PATH_DATA_LAYERS = f"/{API_VERSION}/dataLayers:get"
    PATH_GEO_TIFF = f"/{API_VERSION}/geoTiff:get"

    # ----- geo_tiff layer mapping --------------------------------------------

    #: ``dataLayers:get`` response field -> connector ``layer_type`` value.
    #: Ordered so ``geo_tiff`` rows come back in a stable, documented sequence.
    GEO_TIFF_SCALAR_LAYERS = {
        "dsmUrl": "dsm",
        "rgbUrl": "rgb",
        "maskUrl": "mask",
        "annualFluxUrl": "annual_flux",
        "monthlyFluxUrl": "monthly_flux",
    }

    #: The one repeated URL field: 12 entries, Jan..Dec, one GeoTIFF per month.
    GEO_TIFF_ARRAY_FIELD = "hourlyShadeUrls"
    GEO_TIFF_ARRAY_LAYER = "hourly_shade"

    GEO_TIFF_LAYER_TYPES = list(GEO_TIFF_SCALAR_LAYERS.values()) + [GEO_TIFF_ARRAY_LAYER]

    # ----- shared google.type.* sub-structs -----------------------------------

    #: ``google.type.LatLng``
    LAT_LNG = StructType(
        [
            StructField("latitude", DoubleType(), True),
            StructField("longitude", DoubleType(), True),
        ]
    )

    #: A south-west / north-east pair of ``LatLng``.
    LAT_LNG_BOX = StructType(
        [
            StructField("sw", LAT_LNG, True),
            StructField("ne", LAT_LNG, True),
        ]
    )

    #: ``google.type.Date``.  Deliberately *not* a Spark ``DateType``: the proto
    #: allows partial dates (month/day may legally be 0), which would silently
    #: fail to coerce.
    DATE = StructType(
        [
            StructField("year", LongType(), True),
            StructField("month", LongType(), True),
            StructField("day", LongType(), True),
        ]
    )

    #: ``google.type.Money``.  ``units`` arrives as a *string-encoded* int64 on
    #: the wire; the framework's LongType parser accepts that string form.
    MONEY = StructType(
        [
            StructField("currencyCode", StringType(), True),
            StructField("units", LongType(), True),
            StructField("nanos", LongType(), True),
        ]
    )

    # ----- building_insights nested structs -----------------------------------

    SIZE_AND_SUNSHINE_STATS = StructType(
        [
            StructField("areaMeters2", DoubleType(), True),
            StructField("sunshineQuantiles", ArrayType(DoubleType()), True),
            StructField("groundAreaMeters2", DoubleType(), True),
        ]
    )

    ROOF_SEGMENT_SIZE_AND_SUNSHINE_STATS = StructType(
        [
            StructField("pitchDegrees", DoubleType(), True),
            StructField("azimuthDegrees", DoubleType(), True),
            StructField("stats", SIZE_AND_SUNSHINE_STATS, True),
            StructField("center", LAT_LNG, True),
            StructField("boundingBox", LAT_LNG_BOX, True),
            StructField("planeHeightAtCenterMeters", DoubleType(), True),
        ]
    )

    SOLAR_PANEL = StructType(
        [
            StructField("center", LAT_LNG, True),
            # SolarPanelOrientation enum, kept as its string constant.
            StructField("orientation", StringType(), True),
            StructField("yearlyEnergyDcKwh", DoubleType(), True),
            StructField("segmentIndex", LongType(), True),
        ]
    )

    ROOF_SEGMENT_SUMMARY = StructType(
        [
            StructField("pitchDegrees", DoubleType(), True),
            StructField("azimuthDegrees", DoubleType(), True),
            StructField("panelsCount", LongType(), True),
            StructField("yearlyEnergyDcKwh", DoubleType(), True),
            StructField("segmentIndex", LongType(), True),
        ]
    )

    SOLAR_PANEL_CONFIG = StructType(
        [
            StructField("panelsCount", LongType(), True),
            StructField("yearlyEnergyDcKwh", DoubleType(), True),
            StructField("roofSegmentSummaries", ArrayType(ROOF_SEGMENT_SUMMARY), True),
        ]
    )

    SAVINGS_OVER_TIME = StructType(
        [
            StructField("savingsYear1", MONEY, True),
            StructField("savingsYear20", MONEY, True),
            StructField("presentValueOfSavingsYear20", MONEY, True),
            StructField("savingsLifetime", MONEY, True),
            StructField("presentValueOfSavingsLifetime", MONEY, True),
            StructField("financiallyViable", BooleanType(), True),
        ]
    )

    FINANCIAL_DETAILS = StructType(
        [
            StructField("initialAcKwhPerYear", DoubleType(), True),
            StructField("remainingLifetimeUtilityBill", MONEY, True),
            StructField("federalIncentive", MONEY, True),
            StructField("stateIncentive", MONEY, True),
            StructField("utilityIncentive", MONEY, True),
            StructField("lifetimeSrecTotal", MONEY, True),
            StructField("costOfElectricityWithoutSolar", MONEY, True),
            StructField("netMeteringAllowed", BooleanType(), True),
            StructField("solarPercentage", DoubleType(), True),
            StructField("percentageExportedToGrid", DoubleType(), True),
        ]
    )

    LEASING_SAVINGS = StructType(
        [
            StructField("leasesAllowed", BooleanType(), True),
            StructField("leasesSupported", BooleanType(), True),
            StructField("annualLeasingCost", MONEY, True),
            StructField("savings", SAVINGS_OVER_TIME, True),
        ]
    )

    CASH_PURCHASE_SAVINGS = StructType(
        [
            StructField("outOfPocketCost", MONEY, True),
            StructField("upfrontCost", MONEY, True),
            StructField("rebateValue", MONEY, True),
            StructField("paybackYears", DoubleType(), True),
            StructField("savings", SAVINGS_OVER_TIME, True),
        ]
    )

    #: Same shape as ``CashPurchaseSavings`` plus the loan rate.
    FINANCED_PURCHASE_SAVINGS = StructType(
        [
            StructField("annualLoanPayment", MONEY, True),
            StructField("rebateValue", MONEY, True),
            StructField("loanInterestRate", DoubleType(), True),
            StructField("savings", SAVINGS_OVER_TIME, True),
        ]
    )

    FINANCIAL_ANALYSIS = StructType(
        [
            StructField("monthlyBill", MONEY, True),
            StructField("defaultBill", BooleanType(), True),
            StructField("averageKwhPerMonth", DoubleType(), True),
            StructField("panelConfigIndex", LongType(), True),
            StructField("financialDetails", FINANCIAL_DETAILS, True),
            StructField("leasingSavings", LEASING_SAVINGS, True),
            StructField("cashPurchaseSavings", CASH_PURCHASE_SAVINGS, True),
            StructField("financedPurchaseSavings", FINANCED_PURCHASE_SAVINGS, True),
        ]
    )

    SOLAR_POTENTIAL = StructType(
        [
            StructField("maxArrayPanelsCount", LongType(), True),
            StructField("panelCapacityWatts", DoubleType(), True),
            StructField("panelHeightMeters", DoubleType(), True),
            StructField("panelWidthMeters", DoubleType(), True),
            StructField("panelLifetimeYears", LongType(), True),
            StructField("maxArrayAreaMeters2", DoubleType(), True),
            StructField("maxSunshineHoursPerYear", DoubleType(), True),
            StructField("carbonOffsetFactorKgPerMwh", DoubleType(), True),
            StructField("wholeRoofStats", SIZE_AND_SUNSHINE_STATS, True),
            StructField("buildingStats", SIZE_AND_SUNSHINE_STATS, True),
            StructField(
                "roofSegmentStats",
                ArrayType(ROOF_SEGMENT_SIZE_AND_SUNSHINE_STATS),
                True,
            ),
            StructField("solarPanels", ArrayType(SOLAR_PANEL), True),
            StructField("solarPanelConfigs", ArrayType(SOLAR_PANEL_CONFIG), True),
            StructField("financialAnalyses", ArrayType(FINANCIAL_ANALYSIS), True),
        ]
    )

    #: Only populated when ``additionalInsights=DETECTED_ARRAYS`` is requested.
    DETECTED_ARRAYS = StructType(
        [
            StructField("detectionStatus", StringType(), True),
            StructField("latestCaptureDate", DATE, True),
        ]
    )

    # ----- table schemas ------------------------------------------------------

    BUILDING_INSIGHTS_SCHEMA = StructType(
        [
            StructField("name", StringType(), True),
            StructField("center", LAT_LNG, True),
            StructField("boundingBox", LAT_LNG_BOX, True),
            StructField("imageryDate", DATE, True),
            StructField("imageryProcessedDate", DATE, True),
            StructField("postalCode", StringType(), True),
            StructField("administrativeArea", StringType(), True),
            StructField("statisticalArea", StringType(), True),
            StructField("regionCode", StringType(), True),
            StructField("imageryQuality", StringType(), True),
            StructField("solarPotential", SOLAR_POTENTIAL, True),
            StructField("detectedArrays", DETECTED_ARRAYS, True),
        ]
    )

    DATA_LAYERS_SCHEMA = StructType(
        [
            StructField("imageryDate", DATE, True),
            StructField("imageryProcessedDate", DATE, True),
            StructField("dsmUrl", StringType(), True),
            StructField("rgbUrl", StringType(), True),
            StructField("maskUrl", StringType(), True),
            StructField("annualFluxUrl", StringType(), True),
            StructField("monthlyFluxUrl", StringType(), True),
            StructField("hourlyShadeUrls", ArrayType(StringType()), True),
            StructField("imageryQuality", StringType(), True),
            # Connector-derived: the request parameters are the only stable
            # identity a dataLayers response has.
            StructField("query_latitude", DoubleType(), True),
            StructField("query_longitude", DoubleType(), True),
            StructField("query_radius_meters", DoubleType(), True),
        ]
    )

    GEO_TIFF_SCHEMA = StructType(
        [
            StructField("asset_id", StringType(), True),
            StructField("layer_type", StringType(), True),
            StructField("month_index", LongType(), True),
            StructField("content_type", StringType(), True),
            # Raw GeoTIFF bytes.  Stored as BinaryType rather than a base64
            # string to avoid ~33% size bloat and a pointless encode/decode.
            StructField("data", BinaryType(), True),
            StructField("source_url", StringType(), True),
            StructField("query_latitude", DoubleType(), True),
            StructField("query_longitude", DoubleType(), True),
            StructField("fetched_at", TimestampType(), True),
        ]
    )

    TABLE_SCHEMAS = {
        TABLE_BUILDING_INSIGHTS: BUILDING_INSIGHTS_SCHEMA,
        TABLE_DATA_LAYERS: DATA_LAYERS_SCHEMA,
        TABLE_GEO_TIFF: GEO_TIFF_SCHEMA,
    }

    # ----- table metadata -----------------------------------------------------

    # Every object is a point-in-time lookup: no endpoint accepts an
    # ``updatedSince``-style filter and no response exposes a revision or
    # modification timestamp, so there is no usable cursor anywhere in this API.
    # All three tables are therefore ``snapshot`` with ``cursor_field: None``.
    TABLE_METADATA = {
        TABLE_BUILDING_INSIGHTS: {
            "primary_keys": ["name"],
            "cursor_field": None,
            "ingestion_type": "snapshot",
        },
        TABLE_DATA_LAYERS: {
            "primary_keys": [
                "query_latitude",
                "query_longitude",
                "query_radius_meters",
            ],
            "cursor_field": None,
            "ingestion_type": "snapshot",
        },
        TABLE_GEO_TIFF: {
            "primary_keys": ["asset_id"],
            "cursor_field": None,
            "ingestion_type": "snapshot",
        },
    }


    ########################################################
    # src/databricks/labs/community_connector/sources/google_maps_solar/google_maps_solar.py
    ########################################################

    _TRUTHY = {"true", "t", "yes", "y", "1"}


    class GoogleMapsSolarLakeflowConnect(LakeflowConnect, SupportsPartition):
        """LakeflowConnect implementation for the Google Maps Platform Solar API."""

        def __init__(self, options: dict[str, str]) -> None:
            super().__init__(options)
            self._api_key = options.get("api_key") or options.get("key")
            if not self._api_key:
                raise ValueError(
                    "Google Maps Solar connector requires 'api_key' in options "
                    "(a Google Maps Platform API key with the Solar API enabled)"
                )
            self._base_url = (options.get("base_url") or DEFAULT_BASE_URL).rstrip("/")

        # ----- LakeflowConnect ------------------------------------------------

        def list_tables(self) -> list[str]:
            """Static table list — the Solar API has no discovery endpoint."""
            return list(TABLES)

        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            self._validate_table(table_name)
            return TABLE_SCHEMAS[table_name]

        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            self._validate_table(table_name)
            metadata = dict(TABLE_METADATA[table_name])
            metadata["primary_keys"] = list(metadata["primary_keys"])
            return metadata

        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Single-driver snapshot read across every configured location.

            All three tables are full-refresh, so the returned offset is always
            empty: there is nothing to checkpoint and nothing to resume from.
            """
            self._validate_table(table_name)
            locations = self._resolve_locations(table_options)

            records: list[dict] = []
            for latitude, longitude in locations:
                records.extend(
                    self._read_location(table_name, latitude, longitude, table_options)
                )
            return iter(records), {}

        # ----- SupportsPartition ----------------------------------------------

        def get_partitions(
            self, table_name: str, table_options: dict[str, str]
        ) -> Sequence[dict]:
            """One partition per configured location.

            Each location costs the same number of API calls, so the partitions
            are naturally balanced.  Descriptors carry only primitives so Spark
            can ship them to executors as JSON.
            """
            self._validate_table(table_name)
            return [
                {"latitude": latitude, "longitude": longitude}
                for latitude, longitude in self._resolve_locations(table_options)
            ]

        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read one location's records.  Runs on a Spark executor.

            Self-contained: the HTTP calls are issued with ``requests`` directly
            (no cached ``Session``) and every credential comes from
            ``self.options``, so no driver-side state is required.
            """
            self._validate_table(table_name)
            latitude = float(partition["latitude"])
            longitude = float(partition["longitude"])
            return iter(
                self._read_location(table_name, latitude, longitude, table_options)
            )

        # ----- per-table readers ----------------------------------------------

        def _read_location(
            self,
            table_name: str,
            latitude: float,
            longitude: float,
            table_options: dict[str, str],
        ) -> list[dict]:
            if table_name == TABLE_BUILDING_INSIGHTS:
                return self._read_building_insights(latitude, longitude, table_options)
            if table_name == TABLE_DATA_LAYERS:
                return self._read_data_layers(latitude, longitude, table_options)
            return self._read_geo_tiff(latitude, longitude, table_options)

        def _read_building_insights(
            self, latitude: float, longitude: float, table_options: dict[str, str]
        ) -> list[dict]:
            params = self._location_params(latitude, longitude)
            self._add_quality_params(params, table_options)
            _add_repeated(params, "additionalInsights", table_options.get("additionalInsights"))

            payload = self._get_json(
                PATH_BUILDING_INSIGHTS, params, table_options, DEFAULT_TIMEOUT
            )
            if payload is None:
                return []
            # ``detectedArrays`` is absent unless additionalInsights was requested;
            # a StructType field that is missing must be None, never {}.
            payload.setdefault("detectedArrays", None)
            return [payload]

        def _read_data_layers(
            self, latitude: float, longitude: float, table_options: dict[str, str]
        ) -> list[dict]:
            radius = self._radius_meters(table_options)
            payload = self._fetch_data_layers(latitude, longitude, radius, table_options)
            if payload is None:
                return []

            # The response carries no identifier of its own — the request
            # parameters are the row's only stable identity.
            payload["query_latitude"] = latitude
            payload["query_longitude"] = longitude
            payload["query_radius_meters"] = radius
            return [payload]

        def _read_geo_tiff(
            self, latitude: float, longitude: float, table_options: dict[str, str]
        ) -> list[dict]:
            """Resolve this location's GeoTIFF assets, then download each one.

            The signed URLs minted by ``dataLayers:get`` expire ~1 hour later, so
            the resolve and the downloads deliberately happen back to back inside
            one unit of work rather than across pipeline stages.
            """
            wanted = self._wanted_layer_types(table_options)
            max_assets = int(table_options.get("max_assets_per_location", "20"))

            assets = self._explicit_assets(table_options, wanted)
            if assets is None:
                radius = self._radius_meters(table_options)
                payload = self._fetch_data_layers(
                    latitude, longitude, radius, table_options
                )
                if payload is None:
                    return []
                assets = self._assets_from_data_layers(payload, wanted)

            records = []
            for layer_type, month_index, url_value in assets[:max_assets]:
                record = self._download_geo_tiff(
                    layer_type, month_index, url_value, latitude, longitude, table_options
                )
                if record is not None:
                    records.append(record)
            return records

        # ----- geo_tiff helpers -----------------------------------------------

        @staticmethod
        def _wanted_layer_types(table_options: dict[str, str]) -> set:
            raw = table_options.get("layer_types")
            if not raw:
                return set(GEO_TIFF_LAYER_TYPES)
            wanted = {part.strip() for part in raw.split(",") if part.strip()}
            unknown = wanted - set(GEO_TIFF_LAYER_TYPES)
            if unknown:
                raise ValueError(
                    f"Unknown layer_types {sorted(unknown)}; "
                    f"expected a subset of {GEO_TIFF_LAYER_TYPES}"
                )
            return wanted

        @staticmethod
        def _explicit_assets(
            table_options: dict[str, str], wanted: set
        ) -> list[tuple] | None:
            """Assets from the ``asset_ids`` option, or None to chain via data_layers."""
            raw = table_options.get("asset_ids")
            if not raw:
                return None
            layer_type = table_options.get("layer_type") or "dsm"
            if layer_type not in wanted:
                return []
            return [
                (layer_type, None, part.strip())
                for part in raw.split(",")
                if part.strip()
            ]

        @staticmethod
        def _assets_from_data_layers(payload: dict, wanted: set) -> list[tuple]:
            """Flatten a dataLayers response into ``(layer_type, month_index, url)``.

            ``monthlyFluxUrl`` and ``hourlyShadeUrls`` are omitted by the API for
            narrow ``view`` settings or ``radiusMeters > 175``, so every field is
            treated as optional.
            """
            assets: list[tuple] = []
            for field_name, layer_type in GEO_TIFF_SCALAR_LAYERS.items():
                if layer_type not in wanted:
                    continue
                url_value = payload.get(field_name)
                if url_value:
                    assets.append((layer_type, None, url_value))

            if GEO_TIFF_ARRAY_LAYER in wanted:
                hourly = payload.get(GEO_TIFF_ARRAY_FIELD) or []
                if isinstance(hourly, list):
                    for index, url_value in enumerate(hourly):
                        if url_value:
                            # 1-based month index, Jan..Dec.
                            assets.append((GEO_TIFF_ARRAY_LAYER, index + 1, url_value))
            return assets

        def _download_geo_tiff(
            self,
            layer_type: str,
            month_index: int | None,
            url_value: str,
            latitude: float,
            longitude: float,
            table_options: dict[str, str],
        ) -> dict | None:
            request_url, params, asset_id, source_url = self._geo_tiff_target(url_value)
            params["key"] = self._api_key

            resp = self._request_with_retry(request_url, params, GEO_TIFF_TIMEOUT)
            if resp.status_code == 404 and self._skip_not_found(table_options):
                return None
            if resp.status_code != 200:
                raise RuntimeError(
                    f"geoTiff:get failed for asset {asset_id!r}: "
                    f"HTTP {resp.status_code} {resp.text[:200]}"
                )

            # Plain REST returns the raster bytes as the response body — there is
            # no JSON ``{contentType, data}`` envelope at the wire level (that
            # shape only exists inside Google's generated client libraries).
            return {
                "asset_id": asset_id,
                "layer_type": layer_type,
                "month_index": month_index,
                "content_type": resp.headers.get("Content-Type"),
                "data": resp.content,
                "source_url": source_url,
                "query_latitude": latitude,
                "query_longitude": longitude,
                "fetched_at": datetime.now(timezone.utc).isoformat(),
            }

        def _geo_tiff_target(self, url_value: str) -> tuple[str, dict, str, str]:
            """Resolve a dataLayers URL field into a fetchable request.

            Live responses hand back a fully-formed signed URL, which is used
            verbatim (only ``key`` is appended).  Anything that is not an
            absolute URL is treated as a bare asset id and turned into a
            ``geoTiff:get?id=...`` request — that is what makes the table
            readable both from the ``asset_ids`` option and against the
            in-process source simulator.
            """
            text = str(url_value)
            if text.lower().startswith(("http://", "https://")):
                query = parse_qs(urlsplit(text).query)
                asset_id = (query.get("id") or [text])[0]
                return text, {}, asset_id, text

            asset_id = text
            request_url = f"{self._base_url}{PATH_GEO_TIFF}"
            source_url = f"{request_url}?id={quote(asset_id, safe='')}"
            return request_url, {"id": asset_id}, asset_id, source_url

        # ----- shared request helpers -----------------------------------------

        def _fetch_data_layers(
            self,
            latitude: float,
            longitude: float,
            radius: float,
            table_options: dict[str, str],
        ) -> dict | None:
            params = self._location_params(latitude, longitude)
            params["radiusMeters"] = radius
            params["view"] = table_options.get("view", "FULL_LAYERS")
            if "pixelSizeMeters" in table_options:
                params["pixelSizeMeters"] = table_options["pixelSizeMeters"]
            self._add_quality_params(params, table_options)
            return self._get_json(PATH_DATA_LAYERS, params, table_options, DEFAULT_TIMEOUT)

        def _get_json(
            self,
            path: str,
            params: dict,
            table_options: dict[str, str],
            timeout: int,
        ) -> dict | None:
            """GET a JSON endpoint.  Returns None for a skippable ``NOT_FOUND``."""
            params = dict(params)
            params["key"] = self._api_key
            url = f"{self._base_url}{path}"

            resp = self._request_with_retry(url, params, timeout)
            if resp.status_code == 404 and self._skip_not_found(table_options):
                # Google returns NOT_FOUND wherever it has no coverage.  Such
                # requests are not billed but do count against the QPM quota.
                return None
            if resp.status_code != 200:
                raise RuntimeError(
                    f"GET {path} failed: HTTP {resp.status_code} {resp.text[:300]}"
                )
            return _drop_empty_objects(_as_object(resp.json())) or None

        def _request_with_retry(
            self, url: str, params: dict, timeout: int
        ) -> requests.Response:
            """GET with exponential backoff on 429/5xx.

            A fresh ``requests.get`` is used per call rather than a cached
            ``Session`` so the connector instance stays picklable when Spark
            ships it to executors for partitioned reads.
            """
            backoff = INITIAL_BACKOFF
            resp = None
            last_exc: RequestException | None = None
            for attempt in range(MAX_RETRIES):
                try:
                    resp = requests.get(url, params=params, timeout=timeout)
                except RequestException as exc:
                    last_exc = exc
                else:
                    if resp.status_code not in RETRIABLE_STATUS_CODES:
                        return resp
                if attempt < MAX_RETRIES - 1:
                    sleep_for = backoff
                    if resp is not None:
                        retry_after = (resp.headers.get("Retry-After") or "").strip()
                        if retry_after:
                            try:
                                sleep_for = max(sleep_for, float(retry_after))
                            except ValueError:
                                pass
                    time.sleep(sleep_for)
                    backoff *= 2

            if resp is not None:
                return resp
            raise RuntimeError(f"GET {url} failed after {MAX_RETRIES} attempts: {last_exc}")

        # ----- option plumbing -------------------------------------------------

        def _validate_table(self, table_name: str) -> None:
            if table_name not in TABLES:
                raise ValueError(
                    f"Table '{table_name}' is not supported. Supported tables: {TABLES}"
                )

        def _option(self, table_options: dict[str, str], *names: str) -> str | None:
            """First non-empty value among *names*, table options winning."""
            for source in (table_options or {}, self.options or {}):
                for name in names:
                    value = source.get(name)
                    if value not in (None, ""):
                        return value
            return None

        def _resolve_locations(
            self, table_options: dict[str, str]
        ) -> list[tuple[float, float]]:
            """Parse the configured query location(s).

            There is no discovery endpoint, so a location is mandatory input.  A
            missing one is a configuration error, not an empty result — defaulting
            it would silently ingest data about the wrong building.
            """
            raw = self._option(table_options, "locations")
            if raw:
                locations = []
                for chunk in str(raw).replace("\n", ";").split(";"):
                    chunk = chunk.strip()
                    if not chunk:
                        continue
                    parts = chunk.split(",")
                    if len(parts) != 2:
                        raise ValueError(
                            f"Invalid entry {chunk!r} in 'locations'; expected "
                            "'<latitude>,<longitude>' pairs separated by ';'"
                        )
                    locations.append((float(parts[0]), float(parts[1])))
                if locations:
                    return locations

            latitude = self._option(table_options, "latitude", "location.latitude")
            longitude = self._option(table_options, "longitude", "location.longitude")
            if latitude is None or longitude is None:
                raise ValueError(
                    "The Solar API is a location lookup with no discovery endpoint, "
                    "so a query location is required. Set table option 'locations' "
                    "(e.g. '37.4450,-122.1390') or both 'latitude' and 'longitude'."
                )
            return [(float(latitude), float(longitude))]

        @staticmethod
        def _location_params(latitude: float, longitude: float) -> dict:
            return {
                "location.latitude": latitude,
                "location.longitude": longitude,
            }

        def _radius_meters(self, table_options: dict[str, str]) -> float:
            return float(self._option(table_options, "radiusMeters") or 100)

        def _add_quality_params(
            self, params: dict, table_options: dict[str, str]
        ) -> None:
            params["requiredQuality"] = (
                self._option(table_options, "requiredQuality") or "HIGH"
            )
            exact = self._option(table_options, "exactQualityRequired")
            if exact is not None:
                params["exactQualityRequired"] = str(exact).lower() in _TRUTHY
            _add_repeated(params, "experiments", self._option(table_options, "experiments"))

        def _skip_not_found(self, table_options: dict[str, str]) -> bool:
            value = self._option(table_options, "skip_not_found")
            if value is None:
                return True
            return str(value).lower() in _TRUTHY


    # ----- module-level helpers -----------------------------------------------


    def _add_repeated(params: dict, name: str, raw: str | None) -> None:
        """Attach a repeated enum query param (``experiments[]``-style)."""
        if not raw:
            return
        values = [part.strip() for part in str(raw).split(",") if part.strip()]
        if values:
            params[name] = values


    def _as_object(payload: Any) -> dict:
        """Normalise a single-resource response body to a dict.

        Each Solar API endpoint returns one object.  The in-process source
        simulator may serve a corpus array for the same URL, so a list is
        tolerated by taking its first element rather than failing the read.
        """
        if isinstance(payload, list):
            first = payload[0] if payload else {}
            return dict(first) if isinstance(first, dict) else {}
        if isinstance(payload, dict):
            return dict(payload)
        return {}


    def _drop_empty_objects(value: Any) -> Any:
        """Recursively replace empty JSON objects with ``None``.

        The framework's StructType parser rejects ``{}`` outright and requires
        ``None`` for an absent struct.  Google normally omits empty messages
        entirely, but proto-to-JSON transcoding can emit ``{}`` for a present-
        but-empty message (e.g. a region with no ``leasingSavings``), so this
        normalises the payload once at the boundary.
        """
        if isinstance(value, dict):
            cleaned = {key: _drop_empty_objects(val) for key, val in value.items()}
            return cleaned or None
        if isinstance(value, list):
            return [_drop_empty_objects(item) for item in value]
        return value


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = GoogleMapsSolarLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_community_table_metadata"
    NAMESPACES_TABLE = "_community_namespaces"
    TABLES_TABLE = "_community_tables"
    VIRTUAL_TABLES = (METADATA_TABLE, NAMESPACES_TABLE, TABLES_TABLE)
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"
    NAMESPACE_PREFIX = "namespacePrefix"
    NAMESPACE = "namespace"


    def _decode_list_of_str_option(option_name: str, value: str | None) -> list[str] | None:
        """Decode and validate a JSON-encoded ``list[str]`` Spark option.

        Returns ``None`` if the option is absent; otherwise the parsed list.
        Raises ``ValueError`` with the offending value if the JSON is malformed
        or the decoded value is not a list of strings.
        """
        if value is None:
            return None
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, list) or not all(isinstance(s, str) for s in decoded):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got: {decoded!r}"
            )
        return decoded


    def _decode_dict_option(option_name: str, value: str | None) -> dict:
        """Decode and validate a JSON-encoded ``dict`` Spark option."""
        if value is None:
            return {}
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, dict):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; got: {decoded!r}"
            )
        return decoded


    # PySpark's DataSource API requires camelCase method names and inherits
    # semantics from the parent class, so per-method docstrings are redundant.
    # pylint: disable=invalid-name,missing-function-docstring
    class LakeflowStreamReader(SimpleDataSourceStreamReader, SupportsTriggerAvailableNow):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowPartitionedStreamReader(DataSourceStreamReader, SupportsTriggerAvailableNow):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def getDefaultReadLimit(self):
            # Admission control is the connector's responsibility (e.g. via
            # window_days, max_records_per_batch), not the engine's.  Always
            # ask the engine for ReadAllAvailable.
            return ReadAllAvailable()

        def latestOffset(self, start: dict, limit) -> dict:
            # We declared ReadAllAvailable via getDefaultReadLimit; the engine
            # must respect it.  Anything else means admission-control expectations
            # we do not support — fail loudly rather than silently ignore.
            if not isinstance(limit, ReadAllAvailable):
                raise ValueError(
                    f"LakeflowPartitionedStreamReader only supports ReadAllAvailable; "
                    f"got {type(limit).__name__}. Micro-batch sizing must be controlled "
                    f"by the connector implementation (table_options), not the engine."
                )
            return self.lakeflow_connect.latest_offset(
                self.table_name, self.table_options, start
            )

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name not in VIRTUAL_TABLES:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self.table_name == NAMESPACES_TABLE:
                records = self._read_namespaces()
            elif self.table_name == TABLES_TABLE:
                records = self._read_tables()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_names = _decode_list_of_str_option(
                TABLE_NAME_LIST, self.options.get(TABLE_NAME_LIST)
            ) or []
            table_configs = _decode_dict_option(
                TABLE_CONFIGS, self.options.get(TABLE_CONFIGS)
            )
            all_records = []
            # Preserve caller-supplied table order — caller controls it.
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records

        def _read_namespaces(self):
            # Connectors without SupportsNamespaces are flat — no rows.
            if not isinstance(self.lakeflow_connect, SupportsNamespaces):
                return []
            prefix = _decode_list_of_str_option(
                NAMESPACE_PREFIX, self.options.get(NAMESPACE_PREFIX)
            )
            namespaces = self.lakeflow_connect.list_namespaces(prefix)
            # Sort framework-side for deterministic output regardless of
            # connector iteration order.
            return [{"namespace": ns} for ns in sorted(namespaces)]

        def _read_tables(self):
            namespace_supplied = NAMESPACE in self.options
            if isinstance(self.lakeflow_connect, SupportsNamespaces):
                if not namespace_supplied:
                    raise ValueError(
                        f"option '{NAMESPACE}' is required when reading "
                        f"'{TABLES_TABLE}' against a connector that implements "
                        f"SupportsNamespaces. Pass a JSON-encoded list[str] "
                        f"(use '[]' for root-level tables; walk the tree via "
                        f"'{NAMESPACES_TABLE}' to enumerate every namespace)."
                    )
                namespace = _decode_list_of_str_option(
                    NAMESPACE, self.options[NAMESPACE]
                )
                tables = self.lakeflow_connect.list_tables_in_namespace(namespace)
                return [
                    {"namespace": namespace, TABLE_NAME: tn}
                    for tn in sorted(tables)
                ]
            # Flat connector path. Reject a stray `namespace` option — the
            # caller probably mistook this connector for namespace-aware and
            # silently ignoring the option would mask the bug.
            if namespace_supplied:
                raise ValueError(
                    f"option '{NAMESPACE}' was supplied but the connector does "
                    f"not implement SupportsNamespaces. Either omit the option "
                    f"or use a namespace-aware connector."
                )
            return [
                {"namespace": [], TABLE_NAME: tn}
                for tn in sorted(self.lakeflow_connect.list_tables())
            ]


    class LakeflowSource(DataSource):
        """
        PySpark DataSource base for Lakeflow Connect.

        Two ways the connector implementation is bound:

        - Per-source subclass (wheel / multi-file deployment): subclass and set
          ``_lakeflow_connect_cls``::

              class GmailDataSource(LakeflowSource):
                  _lakeflow_connect_cls = GmailLakeflowConnect

              spark.dataSource.register(GmailDataSource)

        - Merged single-file deployment (SDP): ``_lakeflow_connect_cls`` is left
          ``None`` and the connector is taken from the module-level
          ``LakeflowConnectImpl`` placeholder, which the merge script substitutes
          with the actual implementation class.
        """

        # Per-source subclasses set this. Left ``None`` on the base so the merged
        # single-file path falls back to the ``LakeflowConnectImpl`` placeholder.
        _lakeflow_connect_cls = None

        # Spark format name. Defaults to "lakeflow_connect" because Unity Catalog
        # connection-option injection looks for that exact string. A per-source
        # subclass may override this with its source name once it no longer relies
        # on UC injection (see the commented override in each source's __init__.py).
        _format_name = "lakeflow_connect"

        def __init__(self, options):
            self.options = options
            table = options.get(TABLE_NAME)
            # Catch typos against the framework's reserved virtual-table namespace
            # early — falling through to the connector with an unknown
            # `_community_*` name yields a confusing per-connector error.
            if table and table.startswith("_community_") and table not in VIRTUAL_TABLES:
                raise ValueError(
                    f"unknown framework virtual table '{table}'. Valid framework "
                    f"virtual tables are: {', '.join(VIRTUAL_TABLES)}. "
                    f"For a regular source table, use a name that does not start "
                    f"with '_community_'."
                )
            # Per-source subclasses bind the implementation via _lakeflow_connect_cls.
            # The merged single-file path leaves it None and relies on the
            # LakeflowConnectImpl placeholder (substituted by the merge script).
            connect_cls = type(self)._lakeflow_connect_cls or LakeflowConnectImpl
            self.lakeflow_connect = connect_cls(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return cls._format_name

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            if table == NAMESPACES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                    ]
                )
            if table == TABLES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                        StructField(TABLE_NAME, StringType(), False),
                    ]
                )
            return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
