# ==============================================================================
# Merged Lakeflow Source: microsoft_sharepoint
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from typing import Any, Iterator, Sequence
import json
import time

from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.streaming.datasource import ReadAllAvailable, SupportsTriggerAvailableNow
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
import base64
import requests


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Micro-batch sizing (by row count, time window, etc.) is entirely the
            connector's responsibility — use table_options (e.g. ``window_days``,
            ``max_records_per_batch``) to control it.  The framework always
            requests "all available" and does not pass an admission-control
            hint here.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current committed offset.  ``{}`` on the very
                    first call (from ``initialOffset``), then the last returned
                    end_offset on each subsequent call.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_namespaces.py
    ########################################################

    class SupportsNamespaces(ABC):
        """Mixin for connectors whose tables live under hierarchical namespaces.

        A namespace is a path of zero or more string segments (e.g. ``["org",
        "repo"]`` for GitHub, ``["tenant", "project"]`` for Azure DevOps).
        Connectors with a flat catalog do not need this mixin — the framework
        falls back to :meth:`LakeflowConnect.list_tables` and reports each table
        with an empty namespace.

        Output ordering on the ``_community_namespaces`` and ``_community_tables``
        Spark virtual tables is normalized by the framework via ``sorted(...)``,
        so connector implementations of :meth:`list_namespaces` and
        :meth:`list_tables_in_namespace` are free to return their results in
        any order (including from a :class:`set` or generator).

        Must be used together with :class:`LakeflowConnect`.

        Usage::

            class MyConnector(LakeflowConnect, SupportsNamespaces):
                ...
        """

        @abstractmethod
        def list_namespaces(
            self,
            prefix: list[str] | None = None,
        ) -> list[list[str]]:
            """Return the immediate child namespaces under ``prefix``.

            This method returns one level of *namespace* children only — it
            never returns tables. A namespace can hold tables and child
            namespaces independently; callers must always call
            :meth:`list_tables_in_namespace` for every namespace they care
            about, regardless of whether :meth:`list_namespaces` returned
            children for it. An empty return value just means there are no
            further child namespaces under ``prefix``.

            Walk the full tree by recursing on each returned child.

            Args:
                prefix: A namespace path under which to list children. ``None`` or
                    an empty list lists the root-level namespaces.
            Returns:
                A list of full namespace paths (each path includes the prefix).
            """

        @abstractmethod
        def list_tables_in_namespace(
            self,
            namespace: list[str],
        ) -> list[str]:
            """Return the table names that live directly under ``namespace``.

            Callers that want every table across the whole catalog walk the
            namespace tree via :meth:`list_namespaces` and call this method
            once per leaf — there is no "list everything" shortcut.

            Args:
                namespace: The namespace path. An empty list ``[]`` selects
                    root-level tables (those that live outside any namespace).
            Returns:
                A list of table names. The full ``(namespace, table_name)``
                row exposed on ``_community_tables`` is reconstructed by the
                framework from the namespace the caller already supplied, so
                the connector does not need to echo it back.
            """


    ########################################################
    # src/databricks\labs\community_connector\sources\microsoft_sharepoint\microsoft_sharepoint_schemas.py
    ########################################################

    _IDENTITY_SCHEMA = StructType(
        [
            StructField("id", StringType(), True),
            StructField("displayName", StringType(), True),
        ]
    )

    IDENTITY_SET_SCHEMA = StructType(
        [
            StructField("user", _IDENTITY_SCHEMA, True),
            StructField("application", _IDENTITY_SCHEMA, True),
            StructField("device", _IDENTITY_SCHEMA, True),
        ]
    )
    """identitySet used for createdBy / lastModifiedBy."""

    # listInfo: template and configuration details for a list.
    LIST_INFO_SCHEMA = StructType(
        [
            StructField("contentTypesEnabled", BooleanType(), True),
            StructField("hidden", BooleanType(), True),
            StructField("template", StringType(), True),
        ]
    )

    # itemReference: parent site/list information.  Modelled with the fields Graph
    # commonly populates; unknown extras are dropped by the schema projection.
    ITEM_REFERENCE_SCHEMA = StructType(
        [
            StructField("id", StringType(), True),
            StructField("siteId", StringType(), True),
            StructField("driveId", StringType(), True),
            StructField("driveType", StringType(), True),
            StructField("path", StringType(), True),
        ]
    )

    # sharepointIds on the list resource.
    LIST_SHAREPOINT_IDS_SCHEMA = StructType(
        [
            StructField("listId", StringType(), True),
            StructField("siteId", StringType(), True),
            StructField("siteUrl", StringType(), True),
            StructField("tenantId", StringType(), True),
            StructField("webId", StringType(), True),
        ]
    )

    # sharepointIds on the listItem resource (adds list-item-specific fields).
    ITEM_SHAREPOINT_IDS_SCHEMA = StructType(
        [
            StructField("listId", StringType(), True),
            StructField("listItemId", StringType(), True),
            StructField("listItemUniqueId", StringType(), True),
            StructField("siteId", StringType(), True),
            StructField("siteUrl", StringType(), True),
            StructField("tenantId", StringType(), True),
            StructField("webId", StringType(), True),
        ]
    )

    # contentTypeInfo: {id, name}.
    CONTENT_TYPE_SCHEMA = StructType(
        [
            StructField("id", StringType(), True),
            StructField("name", StringType(), True),
        ]
    )

    # deleted facet, only present on delta responses for removed items.
    DELETED_SCHEMA = StructType(
        [
            StructField("state", StringType(), True),
        ]
    )


    # ---------------------------------------------------------------------------
    # Table schemas
    # ---------------------------------------------------------------------------

    LISTS_SCHEMA = StructType(
        [
            StructField("id", StringType(), False),
            StructField("name", StringType(), True),
            StructField("displayName", StringType(), True),
            StructField("description", StringType(), True),
            StructField("webUrl", StringType(), True),
            StructField("createdDateTime", TimestampType(), True),
            StructField("lastModifiedDateTime", TimestampType(), True),
            StructField("createdBy", IDENTITY_SET_SCHEMA, True),
            StructField("lastModifiedBy", IDENTITY_SET_SCHEMA, True),
            StructField("eTag", StringType(), True),
            StructField("list", LIST_INFO_SCHEMA, True),
            StructField("parentReference", ITEM_REFERENCE_SCHEMA, True),
            StructField("sharepointIds", LIST_SHAREPOINT_IDS_SCHEMA, True),
            StructField("system", BooleanType(), True),
            # Connector-derived lineage column: the site the list belongs to.
            StructField("site_id", StringType(), True),
        ]
    )
    """Schema for the ``lists`` table."""

    LIST_ITEMS_SCHEMA = StructType(
        [
            StructField("id", StringType(), False),
            StructField("contentType", CONTENT_TYPE_SCHEMA, True),
            # Dynamic per-list column values — stored as VARIANT (JSON).
            StructField("fields", VariantType(), True),
            StructField("createdBy", IDENTITY_SET_SCHEMA, True),
            StructField("createdDateTime", TimestampType(), True),
            StructField("lastModifiedBy", IDENTITY_SET_SCHEMA, True),
            StructField("lastModifiedDateTime", TimestampType(), True),
            StructField("eTag", StringType(), True),
            StructField("webUrl", StringType(), True),
            StructField("description", StringType(), True),
            StructField("name", StringType(), True),
            StructField("parentReference", ITEM_REFERENCE_SCHEMA, True),
            StructField("sharepointIds", ITEM_SHAREPOINT_IDS_SCHEMA, True),
            StructField("deleted", DELETED_SCHEMA, True),
            # Connector-derived columns forming the durable composite key.
            StructField("list_id", StringType(), False),
            StructField("site_id", StringType(), True),
        ]
    )
    """Schema for the ``list_items`` table."""


    TABLE_SCHEMAS: dict[str, StructType] = {
        "lists": LISTS_SCHEMA,
        "list_items": LIST_ITEMS_SCHEMA,
    }
    """Mapping of table names to their StructType schemas."""


    # ---------------------------------------------------------------------------
    # Table metadata
    # ---------------------------------------------------------------------------

    TABLE_METADATA: dict[str, dict] = {
        "lists": {
            "primary_keys": ["id"],
            "ingestion_type": "snapshot",
        },
        "list_items": {
            # ``id`` is only unique within a list, so the durable key is composite.
            "primary_keys": ["list_id", "id"],
            "cursor_field": "lastModifiedDateTime",
            "ingestion_type": "cdc_with_deletes",
        },
    }
    """Metadata for each table: primary keys, cursor field, ingestion type."""


    SUPPORTED_TABLES: list[str] = list(TABLE_SCHEMAS.keys())
    """All table names supported by the Microsoft SharePoint connector."""


    # ---------------------------------------------------------------------------
    # HTTP / retry constants
    # ---------------------------------------------------------------------------

    GRAPH_BASE_URL = "https://graph.microsoft.com/v1.0"
    LOGIN_BASE_URL = "https://login.microsoftonline.com"
    GRAPH_SCOPE = "https://graph.microsoft.com/.default"

    # Fields on the list resource that must be $select-ed to surface the normally
    # hidden ``system`` facet.  Graph hides system lists unless system is selected.
    LIST_SELECT_WITH_SYSTEM = (
        "id,name,displayName,description,webUrl,createdDateTime,"
        "lastModifiedDateTime,createdBy,lastModifiedBy,eTag,list,"
        "parentReference,sharepointIds,system"
    )

    RETRIABLE_STATUS_CODES = {429, 500, 502, 503}
    MAX_RETRIES = 5
    INITIAL_BACKOFF = 1.0  # seconds; doubled after each retry
    REQUEST_TIMEOUT = 30  # seconds

    # Default paging caps (small so tests never hang; users can raise them).
    DEFAULT_MAX_PAGES = 100
    DEFAULT_TOP = 200


    ########################################################
    # src/databricks/labs/community_connector/sources/microsoft_sharepoint/microsoft_sharepoint.py
    ########################################################

    _STRUCT_COLUMNS = (
        "contentType",
        "createdBy",
        "lastModifiedBy",
        "parentReference",
        "sharepointIds",
        "list",
        "deleted",
    )


    class GraphHTTPError(RuntimeError):
        """Raised for a non-retriable / exhausted Microsoft Graph HTTP error."""

        def __init__(self, status_code: int, message: str) -> None:
            super().__init__(f"Graph request failed ({status_code}): {message}")
            self.status_code = status_code


    class MicrosoftGraphClient:
        """HTTP client for Microsoft Graph with OAuth 2.0 client-credentials auth.

        Holds only picklable state (credential strings + a cached token string), so
        an instance ships cleanly to Spark executors for partitioned reads.
        """

        def __init__(self, tenant_id: str, client_id: str, client_secret: str) -> None:
            self.tenant_id = tenant_id
            self.client_id = client_id
            self.client_secret = client_secret
            self.base_url = GRAPH_BASE_URL
            self._access_token: str | None = None
            self._token_expiry: datetime | None = None

        def get_access_token(self) -> str:
            """Acquire (and cache) an app-only access token via client credentials."""
            if not self.tenant_id or not self.client_id or not self.client_secret:
                raise ValueError(
                    "Missing required options: tenant_id, client_id and client_secret "
                    "are required for the Microsoft SharePoint connector."
                )

            if (
                self._access_token
                and self._token_expiry
                and datetime.now(timezone.utc) < self._token_expiry
            ):
                return self._access_token

            token_url = f"{LOGIN_BASE_URL}/{self.tenant_id}/oauth2/v2.0/token"
            data = {
                "client_id": self.client_id,
                "client_secret": self.client_secret,
                "scope": GRAPH_SCOPE,
                "grant_type": "client_credentials",
            }

            try:
                response = requests.post(token_url, data=data, timeout=REQUEST_TIMEOUT)
            except requests.RequestException as exc:
                raise RuntimeError(f"Token acquisition request failed: {exc}") from exc

            if response.status_code != 200:
                raise RuntimeError(
                    f"Token acquisition failed ({response.status_code}): "
                    f"{response.text[:500]}"
                )

            token_data = response.json()
            self._access_token = token_data["access_token"]
            expires_in = int(token_data.get("expires_in", 3600))
            # Refresh 5 minutes early to avoid using a token that expires mid-request.
            self._token_expiry = datetime.now(timezone.utc) + timedelta(seconds=expires_in - 300)
            return self._access_token

        def get_json(self, url: str, params: dict | None = None) -> dict:
            """GET a Graph URL, retrying on 429/5xx and honouring ``Retry-After``.

            Raises :class:`GraphHTTPError` on a non-retriable status or once retries
            are exhausted so callers (e.g. delta walks) can react to specific codes
            such as ``410 Gone``.
            """
            backoff = INITIAL_BACKOFF
            for attempt in range(MAX_RETRIES):
                headers = {
                    "Authorization": f"Bearer {self.get_access_token()}",
                    "Accept": "application/json",
                }
                try:
                    response = requests.get(
                        url, params=params, headers=headers, timeout=REQUEST_TIMEOUT
                    )
                except requests.RequestException as exc:
                    if attempt < MAX_RETRIES - 1:
                        time.sleep(backoff)
                        backoff *= 2
                        continue
                    raise RuntimeError(f"Graph request to {url} failed: {exc}") from exc

                if response.status_code == 200:
                    return response.json()

                if response.status_code == 401:
                    # Token may have been revoked; drop the cache and retry once.
                    self._access_token = None
                    self._token_expiry = None
                    if attempt < MAX_RETRIES - 1:
                        continue
                    raise GraphHTTPError(401, response.text[:500])

                if response.status_code in RETRIABLE_STATUS_CODES:
                    if attempt < MAX_RETRIES - 1:
                        # Honour Retry-After when present; the API requires it.
                        retry_after = response.headers.get("Retry-After")
                        wait = int(retry_after) if retry_after and retry_after.isdigit() else backoff
                        time.sleep(wait)
                        backoff *= 2
                        continue
                    raise GraphHTTPError(response.status_code, response.text[:500])

                raise GraphHTTPError(response.status_code, response.text[:500])

            # Unreachable, but keeps type-checkers content.
            raise GraphHTTPError(0, f"Max retries exceeded for {url}")


    def _parse_int_option(table_options: dict[str, str], key: str, default: int) -> int:
        try:
            return int(table_options.get(key, default))
        except (TypeError, ValueError):
            return default


    def _is_deleted_item(item: dict) -> bool:
        """Return True when a delta item represents a deletion.

        Graph marks removed items with a ``deleted`` facet whose ``state`` is
        ``"deleted"``.  Checking the state (rather than mere presence of the facet)
        avoids misclassifying items that carry an unrelated / synthesized
        ``deleted`` sub-object.
        """
        deleted = item.get("deleted")
        return isinstance(deleted, dict) and deleted.get("state") == "deleted"


    def _sanitize_structs(record: dict) -> dict:
        """Convert empty-dict struct columns to ``None`` in place and return record."""
        for key in _STRUCT_COLUMNS:
            if key in record and record[key] == {}:
                record[key] = None
        return record


    class MicrosoftSharepointLakeflowConnect(LakeflowConnect, SupportsPartition):
        """LakeflowConnect implementation for Microsoft SharePoint via Graph."""

        def __init__(self, options: dict[str, str]) -> None:
            super().__init__(options)
            self._client = MicrosoftGraphClient(
                tenant_id=options.get("tenant_id"),
                client_id=options.get("client_id"),
                client_secret=options.get("client_secret"),
            )
            # Resolved site-id cache (site resolution is done once and reused).
            self._site_id_cache: str | None = None

        # ------------------------------------------------------------------
        # Interface: catalog / schema / metadata
        # ------------------------------------------------------------------

        def list_tables(self) -> list[str]:
            return list(SUPPORTED_TABLES)

        def get_table_schema(self, table_name: str, table_options: dict[str, str]) -> StructType:
            self._validate_table(table_name)
            return TABLE_SCHEMAS[table_name]

        def read_table_metadata(self, table_name: str, table_options: dict[str, str]) -> dict:
            self._validate_table(table_name)
            config = TABLE_METADATA[table_name]
            metadata = {
                "primary_keys": list(config["primary_keys"]),
                "ingestion_type": config["ingestion_type"],
            }
            if "cursor_field" in config:
                metadata["cursor_field"] = config["cursor_field"]
            return metadata

        # ------------------------------------------------------------------
        # Interface: reads (single-driver streaming path)
        # ------------------------------------------------------------------

        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            self._validate_table(table_name)
            if table_name == "lists":
                return self._read_lists(table_options)
            return self._read_list_items_delta(start_offset, table_options, deletes=False)

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            self._validate_table(table_name)
            if table_name != "list_items":
                raise ValueError(f"Table '{table_name}' does not support deleted records")
            return self._read_list_items_delta(start_offset, table_options, deletes=True)

        # ------------------------------------------------------------------
        # Interface: SupportsPartition (batch / full-refresh parallelism)
        # ------------------------------------------------------------------

        def get_partitions(
            self, table_name: str, table_options: dict[str, str]
        ) -> list[dict]:
            """Shard a full-refresh read across executors.

            ``lists`` is a single small collection → one partition.  ``list_items``
            is sharded by list so each list's items are read in parallel.
            """
            self._validate_table(table_name)
            site_id = self._resolve_site_id(table_options)
            if table_name == "lists":
                return [{"table": "lists", "site_id": site_id}]

            list_ids = self._resolve_list_ids(site_id, table_options)
            return [
                {"table": "list_items", "site_id": site_id, "list_id": list_id}
                for list_id in list_ids
            ]

        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read one partition's records on a Spark executor."""
            site_id = partition["site_id"]
            if table_name == "lists":
                return iter(self._fetch_lists(site_id, table_options, with_site=True))
            list_id = partition["list_id"]
            return iter(self._fetch_list_items_full(site_id, list_id, table_options))

        # ------------------------------------------------------------------
        # Site / list resolution
        # ------------------------------------------------------------------

        def _resolve_site_id(self, table_options: dict[str, str]) -> str:
            """Resolve the Graph ``site-id`` from options, caching the result.

            Precedence: an explicit ``site_id`` (opaque composite Graph id) wins;
            otherwise a human-friendly ``site_url`` is resolved via colon-syntax
            addressing; otherwise the tenant root site is used.
            """
            explicit = table_options.get("site_id") or self.options.get("site_id")
            if explicit:
                return explicit
            if self._site_id_cache:
                return self._site_id_cache

            site_url = table_options.get("site_url") or self.options.get("site_url")
            if site_url:
                url = f"{self._client.base_url}/sites/{site_url}"
            else:
                url = f"{self._client.base_url}/sites/root"

            data = self._client.get_json(url)
            site_id = data.get("id")
            if not site_id:
                raise RuntimeError(
                    f"Could not resolve a site-id from {url}; response had no 'id'."
                )
            self._site_id_cache = site_id
            return site_id

        def _resolve_list_ids(self, site_id: str, table_options: dict[str, str]) -> list[str]:
            """Return the list-ids to read: an explicit ``list_id`` or all lists."""
            explicit = table_options.get("list_id")
            if explicit:
                return [explicit]
            lists = self._fetch_lists(site_id, table_options, with_site=False)
            return [row["id"] for row in lists if row.get("id")]

        # ------------------------------------------------------------------
        # lists reads
        # ------------------------------------------------------------------

        def _read_lists(
            self, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            site_id = self._resolve_site_id(table_options)
            records = self._fetch_lists(site_id, table_options, with_site=True)
            # snapshot table: no incremental offset.
            return iter(records), {}

        def _fetch_lists(
            self, site_id: str, table_options: dict[str, str], with_site: bool
        ) -> list[dict]:
            """Page through ``/sites/{site-id}/lists`` and return cleaned rows.

            ``include_system=true`` surfaces the normally hidden system lists by
            adding ``system`` to ``$select`` (Graph hides them by default).
            """
            include_system = table_options.get("include_system", "").lower() == "true"
            max_pages = _parse_int_option(table_options, "max_pages_per_batch", DEFAULT_MAX_PAGES)
            top = _parse_int_option(table_options, "top", DEFAULT_TOP)

            url: str | None = f"{self._client.base_url}/sites/{site_id}/lists"
            params: dict | None = {"$top": top}
            if include_system:
                params["$select"] = LIST_SELECT_WITH_SYSTEM

            records: list[dict] = []
            pages = 0
            while url and pages < max_pages:
                data = self._client.get_json(url, params=params)
                params = None  # nextLink already encodes query params
                for raw in data.get("value", []):
                    record = _sanitize_structs(dict(raw))
                    if with_site:
                        record["site_id"] = site_id
                    records.append(record)
                url = data.get("@odata.nextLink")
                pages += 1
            return records

        # ------------------------------------------------------------------
        # list_items reads
        # ------------------------------------------------------------------

        def _build_item_record(self, item: dict, site_id: str, list_id: str) -> dict:
            """Project a raw Graph listItem into a connector record.

            The dynamic ``fields`` facet is serialised to a JSON string so the
            framework can load it into the ``VariantType`` column.
            """
            record = _sanitize_structs(dict(item))
            fields = record.get("fields")
            record["fields"] = json.dumps(fields) if fields else None
            record["list_id"] = list_id
            record["site_id"] = site_id
            return record

        def _fetch_list_items_full(
            self, site_id: str, list_id: str, table_options: dict[str, str]
        ) -> list[dict]:
            """Full (non-delta) read of a list's items with field values expanded."""
            max_pages = _parse_int_option(table_options, "max_pages_per_batch", DEFAULT_MAX_PAGES)
            top = _parse_int_option(table_options, "top", DEFAULT_TOP)

            url: str | None = (
                f"{self._client.base_url}/sites/{site_id}/lists/{list_id}/items"
            )
            # $expand=fields is REQUIRED — column values are absent otherwise.
            params: dict | None = {"$expand": "fields", "$top": top}

            records: list[dict] = []
            pages = 0
            while url and pages < max_pages:
                data = self._client.get_json(url, params=params)
                params = None
                for item in data.get("value", []):
                    records.append(self._build_item_record(item, site_id, list_id))
                url = data.get("@odata.nextLink")
                pages += 1
            return records

        def _read_list_items_delta(
            self, start_offset: dict, table_options: dict[str, str], deletes: bool
        ) -> tuple[Iterator[dict], dict]:
            """Incremental delta read across every in-scope list.

            Yields upserts (``deletes=False``) or delete tombstones
            (``deletes=True``).  Each list keeps its own resume link inside the
            ``links`` offset map; when a list produces no records its prior link is
            kept unchanged so Trigger.AvailableNow converges.
            """
            site_id = self._resolve_site_id(table_options)
            list_ids = self._resolve_list_ids(site_id, table_options)
            max_pages = _parse_int_option(table_options, "max_pages_per_batch", DEFAULT_MAX_PAGES)

            prior_links = (
                start_offset.get("links", {})
                if start_offset and isinstance(start_offset, dict)
                else {}
            )
            new_links = dict(prior_links)

            records: list[dict] = []
            for list_id in list_ids:
                key = f"{site_id}/{list_id}"
                prior_url = prior_links.get(key)
                recs, end_url = self._walk_list_delta(
                    site_id, list_id, prior_url, max_pages, deletes
                )
                records.extend(recs)
                # Graph rotates the deltaLink even with no changes; keep the prior
                # link when this list yielded nothing so the offset can stabilise.
                if prior_url is not None and not recs:
                    new_links[key] = prior_url
                elif end_url:
                    new_links[key] = end_url

            end_offset = {"links": new_links} if new_links else {}
            if start_offset and end_offset == start_offset:
                return iter([]), start_offset
            return iter(records), end_offset

        def _walk_list_delta(
            self,
            site_id: str,
            list_id: str,
            start_url: str | None,
            max_pages: int,
            deletes: bool,
        ) -> tuple[list[dict], str | None]:
            """Walk one list's delta feed; return (records, resume_url).

            ``resume_url`` is the ``@odata.deltaLink`` once the feed is drained, or
            the ``@odata.nextLink`` if paging stopped early at ``max_pages``.
            Handles a stale token (``410 Gone``) by restarting the chain tokenless.
            """
            if start_url:
                url: str | None = start_url
                params: dict | None = None
            else:
                url = f"{self._client.base_url}/sites/{site_id}/lists/{list_id}/items/delta"
                params = {"$expand": "fields"}

            records: list[dict] = []
            resume_url = start_url
            pages = 0
            while url and pages < max_pages:
                try:
                    data = self._client.get_json(url, params=params)
                except GraphHTTPError as exc:
                    if exc.status_code == 410 and start_url is not None:
                        # Stale delta token — restart this list from scratch.
                        return self._walk_list_delta(site_id, list_id, None, max_pages, deletes)
                    raise
                params = None  # nextLink / deltaLink already encode query params

                for item in data.get("value", []):
                    if deletes == _is_deleted_item(item):
                        records.append(self._build_item_record(item, site_id, list_id))

                delta_link = data.get("@odata.deltaLink")
                if delta_link:
                    resume_url = delta_link
                    break
                next_link = data.get("@odata.nextLink")
                if next_link:
                    resume_url = next_link
                    url = next_link
                    pages += 1
                    continue
                # Feed drained but the response carried no deltaLink (e.g. the
                # in-process simulator emits ``@odata.deltaLink: null``).  Fall
                # back to a stable sentinel — the tokenless delta URL — so the
                # offset advances on the first productive read and then compares
                # equal on the next read, letting Trigger.AvailableNow converge.
                resume_url = (
                    f"{self._client.base_url}/sites/{site_id}/lists/{list_id}/items/delta"
                )
                break

            return records, resume_url

        # ------------------------------------------------------------------
        # Helpers
        # ------------------------------------------------------------------

        def _validate_table(self, table_name: str) -> None:
            if table_name not in TABLE_SCHEMAS:
                raise ValueError(
                    f"Table '{table_name}' is not supported. "
                    f"Supported tables: {SUPPORTED_TABLES}"
                )


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = MicrosoftSharepointLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_community_table_metadata"
    NAMESPACES_TABLE = "_community_namespaces"
    TABLES_TABLE = "_community_tables"
    VIRTUAL_TABLES = (METADATA_TABLE, NAMESPACES_TABLE, TABLES_TABLE)
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"
    NAMESPACE_PREFIX = "namespacePrefix"
    NAMESPACE = "namespace"


    def _decode_list_of_str_option(option_name: str, value: str | None) -> list[str] | None:
        """Decode and validate a JSON-encoded ``list[str]`` Spark option.

        Returns ``None`` if the option is absent; otherwise the parsed list.
        Raises ``ValueError`` with the offending value if the JSON is malformed
        or the decoded value is not a list of strings.
        """
        if value is None:
            return None
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, list) or not all(isinstance(s, str) for s in decoded):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got: {decoded!r}"
            )
        return decoded


    def _decode_dict_option(option_name: str, value: str | None) -> dict:
        """Decode and validate a JSON-encoded ``dict`` Spark option."""
        if value is None:
            return {}
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, dict):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; got: {decoded!r}"
            )
        return decoded


    # PySpark's DataSource API requires camelCase method names and inherits
    # semantics from the parent class, so per-method docstrings are redundant.
    # pylint: disable=invalid-name,missing-function-docstring
    class LakeflowStreamReader(SimpleDataSourceStreamReader, SupportsTriggerAvailableNow):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowPartitionedStreamReader(DataSourceStreamReader, SupportsTriggerAvailableNow):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def getDefaultReadLimit(self):
            # Admission control is the connector's responsibility (e.g. via
            # window_days, max_records_per_batch), not the engine's.  Always
            # ask the engine for ReadAllAvailable.
            return ReadAllAvailable()

        def latestOffset(self, start: dict, limit) -> dict:
            # We declared ReadAllAvailable via getDefaultReadLimit; the engine
            # must respect it.  Anything else means admission-control expectations
            # we do not support — fail loudly rather than silently ignore.
            if not isinstance(limit, ReadAllAvailable):
                raise ValueError(
                    f"LakeflowPartitionedStreamReader only supports ReadAllAvailable; "
                    f"got {type(limit).__name__}. Micro-batch sizing must be controlled "
                    f"by the connector implementation (table_options), not the engine."
                )
            return self.lakeflow_connect.latest_offset(
                self.table_name, self.table_options, start
            )

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name not in VIRTUAL_TABLES:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self.table_name == NAMESPACES_TABLE:
                records = self._read_namespaces()
            elif self.table_name == TABLES_TABLE:
                records = self._read_tables()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_names = _decode_list_of_str_option(
                TABLE_NAME_LIST, self.options.get(TABLE_NAME_LIST)
            ) or []
            table_configs = _decode_dict_option(
                TABLE_CONFIGS, self.options.get(TABLE_CONFIGS)
            )
            all_records = []
            # Preserve caller-supplied table order — caller controls it.
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records

        def _read_namespaces(self):
            # Connectors without SupportsNamespaces are flat — no rows.
            if not isinstance(self.lakeflow_connect, SupportsNamespaces):
                return []
            prefix = _decode_list_of_str_option(
                NAMESPACE_PREFIX, self.options.get(NAMESPACE_PREFIX)
            )
            namespaces = self.lakeflow_connect.list_namespaces(prefix)
            # Sort framework-side for deterministic output regardless of
            # connector iteration order.
            return [{"namespace": ns} for ns in sorted(namespaces)]

        def _read_tables(self):
            namespace_supplied = NAMESPACE in self.options
            if isinstance(self.lakeflow_connect, SupportsNamespaces):
                if not namespace_supplied:
                    raise ValueError(
                        f"option '{NAMESPACE}' is required when reading "
                        f"'{TABLES_TABLE}' against a connector that implements "
                        f"SupportsNamespaces. Pass a JSON-encoded list[str] "
                        f"(use '[]' for root-level tables; walk the tree via "
                        f"'{NAMESPACES_TABLE}' to enumerate every namespace)."
                    )
                namespace = _decode_list_of_str_option(
                    NAMESPACE, self.options[NAMESPACE]
                )
                tables = self.lakeflow_connect.list_tables_in_namespace(namespace)
                return [
                    {"namespace": namespace, TABLE_NAME: tn}
                    for tn in sorted(tables)
                ]
            # Flat connector path. Reject a stray `namespace` option — the
            # caller probably mistook this connector for namespace-aware and
            # silently ignoring the option would mask the bug.
            if namespace_supplied:
                raise ValueError(
                    f"option '{NAMESPACE}' was supplied but the connector does "
                    f"not implement SupportsNamespaces. Either omit the option "
                    f"or use a namespace-aware connector."
                )
            return [
                {"namespace": [], TABLE_NAME: tn}
                for tn in sorted(self.lakeflow_connect.list_tables())
            ]


    class LakeflowSource(DataSource):
        """
        PySpark DataSource base for Lakeflow Connect.

        Two ways the connector implementation is bound:

        - Per-source subclass (wheel / multi-file deployment): subclass and set
          ``_lakeflow_connect_cls``::

              class GmailDataSource(LakeflowSource):
                  _lakeflow_connect_cls = GmailLakeflowConnect

              spark.dataSource.register(GmailDataSource)

        - Merged single-file deployment (SDP): ``_lakeflow_connect_cls`` is left
          ``None`` and the connector is taken from the module-level
          ``LakeflowConnectImpl`` placeholder, which the merge script substitutes
          with the actual implementation class.
        """

        # Per-source subclasses set this. Left ``None`` on the base so the merged
        # single-file path falls back to the ``LakeflowConnectImpl`` placeholder.
        _lakeflow_connect_cls = None

        # Spark format name. Defaults to "lakeflow_connect" because Unity Catalog
        # connection-option injection looks for that exact string. A per-source
        # subclass may override this with its source name once it no longer relies
        # on UC injection (see the commented override in each source's __init__.py).
        _format_name = "lakeflow_connect"

        def __init__(self, options):
            self.options = options
            table = options.get(TABLE_NAME)
            # Catch typos against the framework's reserved virtual-table namespace
            # early — falling through to the connector with an unknown
            # `_community_*` name yields a confusing per-connector error.
            if table and table.startswith("_community_") and table not in VIRTUAL_TABLES:
                raise ValueError(
                    f"unknown framework virtual table '{table}'. Valid framework "
                    f"virtual tables are: {', '.join(VIRTUAL_TABLES)}. "
                    f"For a regular source table, use a name that does not start "
                    f"with '_community_'."
                )
            # Per-source subclasses bind the implementation via _lakeflow_connect_cls.
            # The merged single-file path leaves it None and relies on the
            # LakeflowConnectImpl placeholder (substituted by the merge script).
            connect_cls = type(self)._lakeflow_connect_cls or LakeflowConnectImpl
            self.lakeflow_connect = connect_cls(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return cls._format_name

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            if table == NAMESPACES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                    ]
                )
            if table == TABLES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                        StructField(TABLE_NAME, StringType(), False),
                    ]
                )
            return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
